import { useI18n } from "../i18n/I18nProvider";
import { deepTranslateCopy } from "../i18n/deepTranslate";
import type { SupportedLocale } from "../i18n/types";

function translateLocalCopy<T>(source: T, locale: SupportedLocale): T {
  const translated = locale === "en" ? deepTranslateCopy(source, locale) : source;
  if (locale === "fr" || locale === "en") return translated;

  const replacements: Record<Exclude<SupportedLocale, "fr" | "en">, Array<[string, string]>> = {
    es: [["Tous les reseaux", "Todas las redes"], ["Paiement securise", "Pago seguro"], ["Choisir un pack", "Elegir un pack"], ["Votre morceau", "Tu cancion"], ["Une visibilite Spotify", "Visibilidad de Spotify"], ["ciblee", "dirigida"], ["& progressive.", "y progresiva."], ["Quel volume ?", "Que volumen?"], ["Ecoutes", "Reproducciones"], ["Votre campagne", "Tu campana"], ["Pack selectionne", "Pack seleccionado"], ["Pack visibilite Spotify", "Pack de visibilidad Spotify"], ["credit inclus", "credito incluido"], ["Remise incluse", "Descuento incluido"], ["Continuer", "Continuar"], ["Sans engagement", "Sin compromiso"], ["Aucun mot de passe demande", "Sin contrasena"], ["Quel", "Que"], ["morceau", "cancion"], ["promouvoir ?", "quieres promocionar?"], ["Auditeurs mensuels", "Oyentes mensuales"], ["auditeurs mensuels", "oyentes mensuales"], ["Popularite", "Popularidad"], ["Nouveau total", "Nuevo total"], ["Recapitulatif", "Resumen"], ["Plus qu'une", "Solo queda una"], ["etape", "etapa"], ["preparation de la campagne apres confirmation", "preparacion de la campana tras la confirmacion"], ["Pourquoi Fanovera", "Por que Fanovera"], ["Des ecoutes Spotify", "Reproducciones de Spotify"], ["progressives", "progresivas"], ["et soignees.", "y cuidadas."], ["Avis clients", "Opiniones de clientes"], ["Vos questions,", "Tus preguntas,"], ["nos reponses", "nuestras respuestas"]],
    pt: [["Tous les reseaux", "Todas as redes"], ["Paiement securise", "Pagamento seguro"], ["Choisir un pack", "Escolher um pacote"], ["Votre morceau", "Sua faixa"], ["Une visibilite Spotify", "Visibilidade no Spotify"], ["ciblee", "segmentada"], ["& progressive.", "e progressiva."], ["Quel volume ?", "Qual volume?"], ["Ecoutes", "Reproducoes"], ["Votre campagne", "Sua campanha"], ["Pack selectionne", "Pacote selecionado"], ["Pack visibilite Spotify", "Pacote de visibilidade Spotify"], ["credit inclus", "credito incluido"], ["Remise incluse", "Desconto incluido"], ["Continuer", "Continuar"], ["Sans engagement", "Sem compromisso"], ["Aucun mot de passe demande", "Sem senha"], ["Quel", "Qual"], ["morceau", "faixa"], ["promouvoir ?", "quer promover?"], ["Auditeurs mensuels", "Ouvintes mensais"], ["Popularite", "Popularidade"], ["Nouveau total", "Novo total"], ["Recapitulatif", "Resumo"], ["Plus qu'une", "So falta uma"], ["etape", "etapa"], ["preparation de la campagne apres confirmation", "preparacao da campanha apos confirmacao"], ["Pourquoi Fanovera", "Por que Fanovera"], ["Des ecoutes Spotify", "Reproducoes no Spotify"], ["progressives", "progressivas"], ["et soignees.", "e cuidadas."], ["Avis clients", "Avaliacoes de clientes"], ["Vos questions,", "Suas perguntas,"], ["nos reponses", "nossas respostas"]],
    de: [["Tous les reseaux", "Alle Netzwerke"], ["Paiement securise", "Sichere Zahlung"], ["Choisir un pack", "Paket wahlen"], ["Votre morceau", "Dein Track"], ["Une visibilite Spotify", "Spotify-Sichtbarkeit"], ["ciblee", "gezielt"], ["& progressive.", "und progressiv."], ["Quel volume ?", "Welches Volumen?"], ["Ecoutes", "Streams"], ["Votre campagne", "Deine Kampagne"], ["Pack selectionne", "Ausgewahltes Paket"], ["Pack visibilite Spotify", "Spotify-Sichtbarkeitspaket"], ["credit inclus", "inklusive Guthaben"], ["Remise incluse", "Rabatt enthalten"], ["Continuer", "Weiter"], ["Sans engagement", "Ohne Bindung"], ["Aucun mot de passe demande", "Kein Passwort erforderlich"], ["Quel", "Welchen"], ["morceau", "Track"], ["promouvoir ?", "mochtest du bewerben?"], ["Auditeurs mensuels", "Monatliche Horer"], ["Popularite", "Beliebtheit"], ["Nouveau total", "Neue Summe"], ["Recapitulatif", "Zusammenfassung"], ["Plus qu'une", "Nur noch ein"], ["etape", "Schritt"], ["preparation de la campagne apres confirmation", "Kampagnenvorbereitung nach Bestatigung"], ["Pourquoi Fanovera", "Warum Fanovera"], ["Des ecoutes Spotify", "Spotify-Streams"], ["progressives", "progressiv"], ["et soignees.", "und sorgfaltig."], ["Avis clients", "Kundenbewertungen"], ["Vos questions,", "Deine Fragen,"], ["nos reponses", "unsere Antworten"]],
    it: [["Tous les reseaux", "Tutte le reti"], ["Paiement securise", "Pagamento sicuro"], ["Choisir un pack", "Scegli un pacchetto"], ["Votre morceau", "Il tuo brano"], ["Une visibilite Spotify", "Visibilita Spotify"], ["ciblee", "mirata"], ["& progressive.", "e progressiva."], ["Quel volume ?", "Quale volume?"], ["Ecoutes", "Ascolti"], ["Votre campagne", "La tua campagna"], ["Pack selectionne", "Pacchetto selezionato"], ["Pack visibilite Spotify", "Pacchetto visibilita Spotify"], ["credit inclus", "credito incluso"], ["Remise incluse", "Sconto incluso"], ["Continuer", "Continua"], ["Sans engagement", "Senza impegno"], ["Aucun mot de passe demande", "Nessuna password richiesta"], ["Quel", "Quale"], ["morceau", "brano"], ["promouvoir ?", "vuoi promuovere?"], ["Auditeurs mensuels", "Ascoltatori mensili"], ["Popularite", "Popolarita"], ["Nouveau total", "Nuovo totale"], ["Recapitulatif", "Riepilogo"], ["Plus qu'une", "Manca solo un"], ["etape", "passaggio"], ["preparation de la campagne apres confirmation", "preparazione della campagna dopo conferma"], ["Pourquoi Fanovera", "Perche Fanovera"], ["Des ecoutes Spotify", "Ascolti Spotify"], ["progressives", "progressivi"], ["et soignees.", "e curati."], ["Avis clients", "Recensioni clienti"], ["Vos questions,", "Le tue domande,"], ["nos reponses", "le nostre risposte"]],
    tr: [["Tous les reseaux", "Tum aglar"], ["Paiement securise", "Guvenli odeme"], ["Choisir un pack", "Paket sec"], ["Votre morceau", "Parcaniz"], ["Une visibilite Spotify", "Spotify gorunurlugu"], ["ciblee", "hedefli"], ["& progressive.", "ve kademeli."], ["Quel volume ?", "Hangi hacim?"], ["Ecoutes", "Dinlenmeler"], ["Votre campagne", "Kampanyaniz"], ["Pack selectionne", "Secilen paket"], ["Pack visibilite Spotify", "Spotify gorunurluk paketi"], ["credit inclus", "dahil kredi"], ["Remise incluse", "Indirim dahil"], ["Continuer", "Devam et"], ["Sans engagement", "Taahhutsuz"], ["Aucun mot de passe demande", "Sifre gerekmez"], ["Quel", "Hangi"], ["morceau", "parca"], ["promouvoir ?", "one cikarilsin?"], ["Auditeurs mensuels", "Aylik dinleyiciler"], ["Popularite", "Populerlik"], ["Nouveau total", "Yeni toplam"], ["Recapitulatif", "Ozet"], ["Plus qu'une", "Sadece bir"], ["etape", "adim kaldi"], ["preparation de la campagne apres confirmation", "onaydan sonra kampanya hazirligi"], ["Pourquoi Fanovera", "Neden Fanovera"], ["Des ecoutes Spotify", "Spotify dinlenmeleri"], ["progressives", "kademeli"], ["et soignees.", "ve ozenli."], ["Avis clients", "Musteri yorumlari"], ["Vos questions,", "Sorulariniz,"], ["nos reponses", "cevaplarimiz"]],
  };

  const walk = (value: unknown): unknown => {
    if (typeof value === "string") {
      let text = replacements[locale].reduce((current, [from, to]) => current.replaceAll(from, to), value);
      text = text.replaceAll("auditeurs mensuels", {
        es: "oyentes mensuales",
        pt: "ouvintes mensais",
        de: "monatliche Horer",
        it: "ascoltatori mensili",
        tr: "aylik dinleyiciler",
      }[locale]);
      return text;
    }
    if (Array.isArray(value)) return value.map(walk);
    if (value && typeof value === "object") return Object.fromEntries(Object.entries(value).map(([key, val]) => [key, walk(val)]));
    return value;
  };

  return walk(translated) as T;
}

const copy = {
  fr: {
    header: { allNetworks: "Tous les reseaux", tracking: "Suivi", ratingText: "2 348 avis", home: "Accueil" },
    stepper: ["Choisir un pack", "Votre morceau", "Paiement securise"],
    step1: {
      titleBefore: "Une visibilite Spotify", titleFocus: "ciblee", titleAfter: "& progressive.", volume: "Quel volume ?", audience: "Ecoutes", included: "inclus", campaign: "Votre campagne", selectedPack: "Pack selectionne", visibilityPack: "Pack visibilite Spotify", includedCredit: "credit inclus", total: "Total", discount: "Remise incluse", continue: "Continuer", reassurance: "Sans engagement · Aucun mot de passe demande",
    },
    step2: {
      titleBefore: "Quel", titleFocus: "morceau", titleAfter: "promouvoir ?", intro: "Collez le lien Spotify de votre morceau, ou cherchez par titre + artiste. Aucun mot de passe demande.", searchMode: "Titre + artiste", urlMode: "Lien Spotify", urlLabel: "Lien de votre morceau Spotify", invalidUrl: "Lien invalide. Exemple : https://open.spotify.com/track/xxxxxxxxxxxxxxxxxxxxxx", trackLabel: "Titre du morceau", artistLabel: "Artiste", notFound: "Morceau introuvable sur Spotify.", emailLabel: "Votre e-mail (pour le recu)", emailPlaceholder: "vous@exemple.com", emailHint: "On vous envoie uniquement votre facture. Pas de spam, jamais.", back: "Retour", pay: "Aller au paiement", loading: "Chargement...", trackFallback: "Votre morceau", artistFallback: "Artiste", totalStreams: "Ecoutes totales", monthlyListeners: "Auditeurs mensuels", popularity: "Popularite", newTotal: "Nouveau total",
      errors: { missingUrl: "Collez le lien Spotify de votre morceau.", invalidUrl: "Lien Spotify invalide. Format : open.spotify.com/track/...", missingSearch: "Renseignez le titre et l'artiste.", verifying: "Recherche du morceau en cours...", notFound: "Morceau introuvable sur Spotify.", missingTrack: "Morceau non trouve.", email: "Entrez votre e-mail pour recevoir le recu." },
    },
    step3: { titleBefore: "Plus qu'une", titleFocus: "etape", titleAfter: ".", subtitle: "Paiement securise · preparation de la campagne apres confirmation.", summary: "Recapitulatif", recipient: "Morceau destinataire", edit: "Modifier", trackFallback: "Votre morceau", visibilityPack: "Pack visibilite Spotify", includedCredit: "credit inclus", campaignCredit: "Credit de campagne", free: "OFFERT", coupon: "Code promo", couponPlaceholder: "CODE PROMO", applied: "✓ Applique", apply: "Appliquer", saving: "✓ -5% applique · economie", total: "Total TTC", securePayment: "Paiement securise", legalBefore: "En finalisant le paiement vous acceptez nos", legalAfter: "Aucun abonnement cache.", terms: "CGV", gdpr: "RGPD", backToPacks: "Retour au choix des packs" },
    why: { eyebrow: "Pourquoi Fanovera", title1: "Des ecoutes Spotify", title2: "progressives", title3: "et soignees.", items: [["Audience ciblee", "Notre IA aide a presenter votre morceau a une audience coherente avec votre genre musical."], ["Compte preserve", "Aucun acces au compte, aucune publication a votre place, aucune action directe sur votre profil."], ["Sans mot de passe", "Juste le lien public de votre morceau pour preparer la campagne de visibilite."], ["Suivi inclus", "Si le volume prevu n'est pas atteint, notre support verifie et prolonge la campagne."]] },
    reviews: { eyebrow: "Avis clients", rating: "2 348 avis", dates: ["il y a 2 jours", "il y a 7 jours", "il y a 5 jours", "il y a 10 jours", "il y a 5 jours", "il y a 12 jours", "il y a 14 jours", "il y a 15 jours"], texts: ["Progression reguliere et campagne bien suivie. Je recommande.", "Mise en route rapide, suivi clair et rythme progressif.", "Les ecoutes ont augmente progressivement sur 10 jours.", "Premiere campagne Spotify, service serieux et suivi clair.", "Bonne progression sur mon EP en plusieurs semaines.", "Rien a redire, la progression correspond a ce qui etait annonce.", "Service client reactif et suivi au rendez-vous.", "Mes auditeurs mensuels ont progresse de facon reguliere."] },
    faq: { titleBefore: "Vos questions,", titleFocus: "nos reponses", items: [["Comment fonctionne la mise en avant ?", "Nous preparons une campagne de visibilite autour de votre morceau Spotify et de votre thematique. L'objectif est de presenter votre contenu a une audience plus pertinente, avec un rythme progressif et mesure."], ["Est-ce que je dois vous donner mon mot de passe ?", "Jamais. Nous avons uniquement besoin du lien Spotify public de votre morceau. Aucun acces au compte n'est demande."], ["Est-ce que vous agissez sur mon compte ?", "Non. Nous ne nous connectons pas a votre compte et nous ne publions rien a votre place. Le service s'appuie sur une mise en avant externe et progressive."], ["Quand la campagne demarre-t-elle ?", "La preparation demarre apres confirmation du paiement. Le deploiement est progressif et peut s'etaler sur plusieurs jours selon le volume choisi."], ["Que se passe-t-il si le volume n'est pas atteint ?", "Notre support verifie la campagne et peut prolonger la mise en avant sans frais supplementaires lorsque le volume prevu n'est pas atteint."], ["Les statistiques apparaissent-elles tout de suite ?", "Les statistiques peuvent varier selon les controles et delais propres a Spotify. Le deploiement reste progressif et suivi."]] },
    footer: { desc: "Strategie de presence en ligne assistee par IA. Campagnes ciblees, suivi clair et progression mesuree.", networks: "Reseaux", help: "Aide", how: "Comment ca marche", support: "Support campagne", tracking: "Suivi de commande", legal: "Legal", legalNotice: "Mentions legales", privacy: "Confidentialite", cookies: "Cookies", madeIn: "Made in Paris" },
  },
  en: {
    header: { allNetworks: "All networks", tracking: "Tracking", ratingText: "2,348 reviews", home: "Home" },
    stepper: ["Choose a pack", "Your track", "Secure payment"],
    step1: { titleBefore: "Targeted Spotify visibility", titleFocus: "focused", titleAfter: "and progressive.", volume: "Which volume?", audience: "Streams", included: "included", campaign: "Your campaign", selectedPack: "Selected pack", visibilityPack: "Spotify visibility pack", includedCredit: "included credit", total: "Total", discount: "Discount included", continue: "Continue", reassurance: "No commitment · No password required" },
    step2: { titleBefore: "Which", titleFocus: "track", titleAfter: "would you like to promote?", intro: "Paste your Spotify track link, or search by title + artist. No password required.", searchMode: "Title + artist", urlMode: "Spotify link", urlLabel: "Your Spotify track link", invalidUrl: "Invalid link. Example: https://open.spotify.com/track/xxxxxxxxxxxxxxxxxxxxxx", trackLabel: "Track title", artistLabel: "Artist", notFound: "Track not found on Spotify.", emailLabel: "Your email (for the receipt)", emailPlaceholder: "you@example.com", emailHint: "We only send your invoice. No spam, ever.", back: "Back", pay: "Go to payment", loading: "Loading...", trackFallback: "Your track", artistFallback: "Artist", totalStreams: "Total streams", monthlyListeners: "Monthly listeners", popularity: "Popularity", newTotal: "New total", errors: { missingUrl: "Paste your Spotify track link.", invalidUrl: "Invalid Spotify link. Format: open.spotify.com/track/...", missingSearch: "Enter the title and artist.", verifying: "Track search in progress...", notFound: "Track not found on Spotify.", missingTrack: "Track not found.", email: "Enter your email to receive the receipt." } },
    step3: { titleBefore: "One", titleFocus: "step", titleAfter: "left.", subtitle: "Secure payment · campaign preparation after confirmation.", summary: "Summary", recipient: "Recipient track", edit: "Edit", trackFallback: "Your track", visibilityPack: "Spotify visibility pack", includedCredit: "included credit", campaignCredit: "Campaign credit", free: "FREE", coupon: "Promo code", couponPlaceholder: "PROMO CODE", applied: "✓ Applied", apply: "Apply", saving: "✓ -5% applied · saving", total: "Total incl. tax", securePayment: "Secure payment", legalBefore: "By completing payment, you accept our", legalAfter: "No hidden subscription.", terms: "Terms", gdpr: "GDPR", backToPacks: "Back to pack selection" },
    why: { eyebrow: "Why Fanovera", title1: "Progressive", title2: "Spotify streams", title3: "with careful delivery.", items: [["Focused audience", "Our AI helps present your track to an audience aligned with your music genre."], ["Account protected", "No account access, no posting on your behalf, and no direct action on your profile."], ["No password", "Only your public track link is needed to prepare the visibility campaign."], ["Follow-up included", "If the planned volume is not reached, our support team reviews and extends the campaign."]] },
    reviews: { eyebrow: "Customer reviews", rating: "2,348 reviews", dates: ["2 days ago", "7 days ago", "5 days ago", "10 days ago", "5 days ago", "12 days ago", "14 days ago", "15 days ago"], texts: ["Steady progress and a well-monitored campaign. I recommend it.", "Fast setup, clear tracking and a progressive pace.", "Streams increased gradually over 10 days.", "First Spotify campaign, serious service and clear follow-up.", "Good progress on my EP over several weeks.", "Nothing to add, the progress matched what was announced.", "Responsive support and reliable follow-up.", "My monthly listeners grew at a steady pace."] },
    faq: { titleBefore: "Your questions,", titleFocus: "our answers", items: [["How does the visibility campaign work?", "We prepare a visibility campaign around your Spotify track and topic. The goal is to present your content to a more relevant audience, with a measured and progressive pace."], ["Do I need to give you my password?", "Never. We only need the public Spotify link for your track. No account access is requested."], ["Do you act on my account?", "No. We do not log into your account and we do not publish anything on your behalf. The service relies on external and progressive promotion."], ["When does the campaign start?", "Preparation starts after payment confirmation. Deployment is progressive and can span several days depending on the selected volume."], ["What happens if the volume is not reached?", "Our support team reviews the campaign and can extend the promotion at no extra cost when the planned volume is not reached."], ["Do stats appear immediately?", "Stats can vary depending on Spotify's own checks and delays. Deployment remains progressive and monitored."]] },
    footer: { desc: "AI-assisted online presence strategy. Focused campaigns, clear tracking and measured progress.", networks: "Networks", help: "Help", how: "How it works", support: "Campaign support", tracking: "Order tracking", legal: "Legal", legalNotice: "Legal notice", privacy: "Privacy", cookies: "Cookies", madeIn: "Made in Paris" },
  },
} as const;

type Widen<T> = T extends string ? string : T extends readonly (infer U)[] ? readonly Widen<U>[] : T extends object ? { readonly [K in keyof T]: Widen<T[K]> } : T;
type SpotifyCopy = Widen<(typeof copy)["en"]>;

const localized: Record<SupportedLocale, SpotifyCopy> = {
  fr: copy.fr,
  en: copy.en,
  es: translateLocalCopy(copy.fr, "es"),
  pt: translateLocalCopy(copy.fr, "pt"),
  de: translateLocalCopy(copy.fr, "de"),
  it: translateLocalCopy(copy.fr, "it"),
  tr: translateLocalCopy(copy.fr, "tr"),
};

export function useSpotifyCopy() {
  const { locale } = useI18n();
  const manualLocale =
    typeof window !== "undefined" && window.localStorage.getItem("fanovera_locale_mode") === "manual"
      ? (window.localStorage.getItem("fanovera_locale") as SupportedLocale | null)
      : null;
  return localized[manualLocale || locale] || copy.fr;
}
