import { useI18n } from "../i18n/I18nProvider";
import { deepTranslateCopy } from "../i18n/deepTranslate";
import type { SupportedLocale } from "../i18n/types";
import { applyPerformanceProductCopy } from "../lib/performanceCopy";
import { useMarketingMode } from "../marketing/MarketingModeProvider";

const copy = {
  fr: {
    header: { allNetworks: "Tous les réseaux", tracking: "Suivi", ratingText: "2 348 avis", home: "Accueil" },
    stepper: ["Choisir un pack", "Votre profil", "Paiement sécurisé"],
    step1: { titleBefore: "Une visibilité LinkedIn", titleFocus: "ciblée", titleAfter: "& progressive.", volume: "Quel volume ?", audience: "Audience", included: "inclus", campaign: "Votre campagne", selectedPack: "Pack sélectionné", visibilityPack: "Pack visibilité LinkedIn", includedCredit: "crédit inclus", total: "Total", discount: "Remise incluse", continue: "Continuer", reassurance: "Sans engagement - Aucun mot de passe demandé" },
    step2: { titleBefore: "Quel", titleFocus: "profil", titleAfter: "promouvoir ?", intro: "Collez le lien de votre profil LinkedIn ou votre identifiant. Aucun mot de passe, aucun accès demandé. Le profil doit être public.", usernameLabel: "Lien ou identifiant LinkedIn", usernamePlaceholder: "linkedin.com/in/votre-profil", invalidFormat: "Format invalide. Ex : linkedin.com/in/votre-profil ou votre-profil", notFound: "Profil LinkedIn introuvable.", emailLabel: "Votre e-mail (pour le reçu)", emailPlaceholder: "vous@exemple.com", emailHint: "On vous envoie uniquement votre facture. Pas de spam, jamais.", back: "Retour", pay: "Aller au paiement", errors: { username: "Collez le lien ou l'identifiant de votre profil LinkedIn.", invalid: "Format invalide. Ex : linkedin.com/in/votre-profil ou votre-profil", email: "Entrez votre e-mail pour recevoir le reçu." } },
    step3: { titleBefore: "Plus qu'une", titleFocus: "étape", titleAfter: ".", subtitle: "Paiement sécurisé - préparation de la campagne après confirmation.", summary: "Récapitulatif", recipient: "Profil destinataire", fallbackRecipient: "Votre profil", edit: "Modifier", visibilityPack: "Pack visibilité LinkedIn", includedCredit: "crédit inclus", included: "inclus", campaignCredit: "Crédit de campagne", free: "OFFERT", coupon: "Code promo", couponPlaceholder: "CODE PROMO", applied: "Appliqué", apply: "Appliquer", saving: "-5% appliqué - économie", total: "Total TTC", securePayment: "Paiement sécurisé", legalBefore: "En finalisant le paiement vous acceptez nos", legalAfter: "Aucun abonnement caché.", gdpr: "RGPD", backToPacks: "Retour au choix des packs" },
    why: { eyebrow: "Pourquoi Fanovera", title1: "Une présence LinkedIn", title2: "progressive", title3: "et soignée.", items: [["Audience B2B ciblée", "Notre IA aide à présenter votre profil à une audience professionnelle cohérente avec votre secteur."], ["Compte préservé", "Aucun accès au compte, aucune publication à votre place, aucune action directe sur votre profil."], ["Sans mot de passe", "Juste le lien public de votre profil pour préparer la campagne de visibilité."], ["Suivi inclus", "Si le volume prévu n'est pas atteint, notre support vérifie et peut prolonger la campagne."]] },
    reviews: { eyebrow: "Avis clients", rating: "2 348 avis", dates: ["il y a 2 jours", "il y a 7 jours", "il y a 5 jours", "il y a 10 jours", "il y a 5 jours", "il y a 12 jours", "il y a 14 jours", "il y a 15 jours"], texts: ["Campagne claire pour mon profil professionnel, progression régulière.", "Mise en route rapide et suivi sérieux.", "Mon profil ressort mieux dans les recherches.", "Parfait pour travailler mon personal branding.", "Excellent service, accompagnement propre sur plusieurs semaines.", "Progression conforme à ce qui était annoncé.", "Service client réactif et suivi au rendez-vous.", "Bonne progression continue pour ma présence LinkedIn."] },
    faq: { titleBefore: "Vos questions,", titleFocus: "nos réponses", items: [["Comment fonctionne la mise en avant ?", "Nous préparons une campagne de visibilité autour de votre profil LinkedIn et de votre thématique. L'objectif est de présenter votre profil à une audience plus pertinente, avec un rythme progressif et mesuré."], ["Est-ce que je dois vous donner mon mot de passe ?", "Jamais. Nous avons uniquement besoin du lien public de votre profil LinkedIn. Aucun accès au compte n'est demandé."], ["Est-ce que vous agissez sur mon compte ?", "Non. Nous ne nous connectons pas à votre compte et nous ne publions rien à votre place. Le service s'appuie sur une mise en avant externe et progressive."], ["Quand la campagne démarre-t-elle ?", "La préparation démarre après confirmation du paiement. Le déploiement est progressif et peut s'étaler sur plusieurs jours selon le volume choisi."], ["Que se passe-t-il si le volume n'est pas atteint ?", "Notre support vérifie la campagne et peut prolonger la mise en avant sans frais supplémentaires lorsque le volume prévu n'est pas atteint."], ["Est-ce que cela peut aider ma visibilité professionnelle ?", "Oui. Une mise en avant progressive peut soutenir votre présence B2B et donner plus de contexte à vos contenus."]] },
    footer: { desc: "Stratégie de présence en ligne assistée par IA. Campagnes ciblées, suivi clair et progression mesurée.", networks: "Réseaux", help: "Aide", how: "Comment ça marche", support: "Support campagne", tracking: "Suivi de commande", legal: "Légal", legalNotice: "Mentions légales", terms: "CGV", privacy: "Confidentialité", cookies: "Cookies", made: "Made in Paris" },
  },
  en: {
    header: { allNetworks: "All networks", tracking: "Tracking", ratingText: "2,348 reviews", home: "Home" },
    stepper: ["Choose a pack", "Your profile", "Secure payment"],
    step1: { titleBefore: "Targeted LinkedIn visibility", titleFocus: "focused", titleAfter: "and progressive.", volume: "Which volume?", audience: "Audience", included: "included", campaign: "Your campaign", selectedPack: "Selected pack", visibilityPack: "LinkedIn visibility pack", includedCredit: "included credit", total: "Total", discount: "Discount included", continue: "Continue", reassurance: "No commitment - No password required" },
    step2: { titleBefore: "Which", titleFocus: "profile", titleAfter: "would you like to promote?", intro: "Paste your LinkedIn profile link or handle. No password and no account access requested. The profile must be public.", usernameLabel: "LinkedIn link or handle", usernamePlaceholder: "linkedin.com/in/your-profile", invalidFormat: "Invalid format. Example: linkedin.com/in/your-profile or your-profile", notFound: "LinkedIn profile not found.", emailLabel: "Your email (for the receipt)", emailPlaceholder: "you@example.com", emailHint: "We only send your invoice. No spam, ever.", back: "Back", pay: "Go to payment", errors: { username: "Paste your LinkedIn profile link or handle.", invalid: "Invalid format. Example: linkedin.com/in/your-profile or your-profile", email: "Enter your email to receive the receipt." } },
    step3: { titleBefore: "One", titleFocus: "step", titleAfter: "left.", subtitle: "Secure payment - campaign preparation after confirmation.", summary: "Summary", recipient: "Recipient profile", fallbackRecipient: "Your profile", edit: "Edit", visibilityPack: "LinkedIn visibility pack", includedCredit: "included credit", included: "included", campaignCredit: "Campaign credit", free: "FREE", coupon: "Promo code", couponPlaceholder: "PROMO CODE", applied: "Applied", apply: "Apply", saving: "-5% applied - saving", total: "Total incl. tax", securePayment: "Secure payment", legalBefore: "By completing payment, you accept our", legalAfter: "No hidden subscription.", gdpr: "GDPR", backToPacks: "Back to pack selection" },
    why: { eyebrow: "Why Fanovera", title1: "A progressive,", title2: "well-managed", title3: "LinkedIn presence.", items: [["Focused B2B audience", "Our AI helps present your profile to a professional audience aligned with your field."], ["Account protected", "No account access, no posting on your behalf, and no direct action on your profile."], ["No password", "Only your public profile link is needed to prepare the visibility campaign."], ["Follow-up included", "If the planned volume is not reached, our support team reviews and can extend the campaign."]] },
    reviews: { eyebrow: "Customer reviews", rating: "2,348 reviews", dates: ["2 days ago", "7 days ago", "5 days ago", "10 days ago", "5 days ago", "12 days ago", "14 days ago", "15 days ago"], texts: ["Clear campaign for my professional profile, steady progress.", "Fast setup and serious follow-up.", "My profile appears better in searches.", "Perfect for working on my personal branding.", "Excellent service with clean support over several weeks.", "Progress matched what was announced.", "Responsive customer support and reliable follow-up.", "Good continuous progress for my LinkedIn presence."] },
    faq: { titleBefore: "Your questions,", titleFocus: "our answers", items: [["How does the visibility campaign work?", "We prepare a visibility campaign around your LinkedIn profile and topic. The goal is to present your profile to a more relevant audience, with a measured and progressive pace."], ["Do I need to give you my password?", "Never. We only need your public LinkedIn profile link. No account access is requested."], ["Do you act on my account?", "No. We do not log into your account and we do not publish anything on your behalf. The service relies on an external and progressive promotion."], ["When does the campaign start?", "Preparation starts after payment confirmation. Deployment is progressive and can span several days depending on the selected volume."], ["What happens if the volume is not reached?", "Our support team reviews the campaign and can extend the promotion at no extra cost when the planned volume is not reached."], ["Can this help my professional visibility?", "Yes. Progressive promotion can support your B2B presence and give more context to your content."]] },
    footer: { desc: "AI-assisted online presence strategy. Focused campaigns, clear tracking and measured progress.", networks: "Networks", help: "Help", how: "How it works", support: "Campaign support", tracking: "Order tracking", legal: "Legal", legalNotice: "Legal notice", terms: "Terms", privacy: "Privacy", cookies: "Cookies", made: "Made in Paris" },
  },
};

type LinkedinCopy = (typeof copy)[keyof typeof copy];

const localized: Record<SupportedLocale, LinkedinCopy> = {
  fr: copy.fr,
  en: copy.en,
  es: deepTranslateCopy(copy.fr, "es"),
  pt: deepTranslateCopy(copy.fr, "pt"),
  de: deepTranslateCopy(copy.fr, "de"),
  it: deepTranslateCopy(copy.fr, "it"),
  tr: deepTranslateCopy(copy.fr, "tr"),
};

export function useLinkedinCopy() {
  const { locale } = useI18n();
  const { mode } = useMarketingMode();
  return applyPerformanceProductCopy(localized[locale] || copy.fr, {
    locale,
    mode,
    product: "LinkedIn",
    audience: "Audience",
  });
}
