import { useI18n } from "../i18n/I18nProvider";
import type { SupportedLocale } from "../i18n/types";
import { applyPerformanceProductCopy, applyBlackhatProductCopy, appendNoCommitmentFaq } from "../lib/performanceCopy";
import { useMarketingMode } from "../marketing/MarketingModeProvider";

const copy = {
  fr: {
    header: { allNetworks: "Tous les réseaux", tracking: "Suivi", ratingText: "2 348 avis", home: "Accueil" },
    stepper: ["Choisir un pack", "Votre profil", "Paiement sécurisé"],
    step1: { titleBefore: "Une visibilité LinkedIn", titleFocus: "ciblée", titleAfter: "& progressive.", volume: "Quel volume ?", audience: "Abonnés", included: "inclus", campaign: "Votre campagne", selectedPack: "Pack sélectionné", visibilityPack: "Pack visibilité LinkedIn", includedCredit: "crédit inclus", total: "Total", discount: "Remise incluse", continue: "Continuer", reassurance: "Sans engagement - Aucun mot de passe - Démarrage sous 1–6 h" },
    step2: { titleBefore: "Quel", titleFocus: "profil ou page", titleAfter: "promouvoir ?", intro: "Collez le lien de votre profil ou de votre page LinkedIn. Aucun mot de passe, aucun accès demandé. Le profil ou la page doit être public.", usernameLabel: "Lien LinkedIn (profil ou page)", invalidFormat: "Format invalide. Ex : linkedin.com/in/votre-profil ou linkedin.com/company/votre-entreprise", notFound: "Profil ou page LinkedIn introuvable.", emailLabel: "Votre e-mail", emailPlaceholder: "vous@exemple.com", emailHint: "Pour le reçu + suivi de commande", back: "Retour", pay: "Aller au paiement", errors: { username: "Collez le lien de votre profil ou page LinkedIn.", invalid: "Format invalide. Ex : linkedin.com/in/votre-profil ou linkedin.com/company/votre-entreprise", email: "Entrez votre e-mail pour recevoir le reçu.", emailIncomplete: "Il y a une faute dans votre e-mail ?" } },
    step3: { titleBefore: "Plus qu'une", titleFocus: "étape", titleAfter: ".", subtitle: "Paiement sécurisé - préparation de la campagne après confirmation.", summary: "Récapitulatif", recipient: "Profil destinataire", fallbackRecipient: "Votre profil", edit: "Modifier", visibilityPack: "Pack visibilité LinkedIn", includedCredit: "crédit inclus", included: "inclus", campaignCredit: "Crédit de campagne", free: "OFFERT", coupon: "Code promo", couponPlaceholder: "CODE PROMO", applied: "Appliqué", apply: "Appliquer", saving: "-5% appliqué - économie", total: "Total TTC", securePayment: "Paiement sécurisé", legalBefore: "En finalisant le paiement vous acceptez nos", legalAfter: "Aucun abonnement caché.", gdpr: "RGPD", backToPacks: "Retour au choix des packs" },
    why: { eyebrow: "Pourquoi Fanovera", title1: "Une présence LinkedIn", title2: "progressive", title3: "et soignée.", items: [["Audience B2B ciblée", "Notre IA aide à présenter votre profil à une audience professionnelle cohérente avec votre secteur."], ["Compte préservé", "Aucun accès au compte, aucune publication à votre place, aucune action directe sur votre profil."], ["Sans mot de passe", "Juste le lien public de votre profil pour préparer la campagne de visibilité."], ["Suivi inclus", "Si le volume prévu n'est pas atteint, notre support vérifie et peut prolonger la campagne."]] },
    reviews: { eyebrow: "Avis clients", rating: "2 348 avis", dates: ["il y a 2 jours", "il y a 7 jours", "il y a 5 jours", "il y a 10 jours", "il y a 5 jours", "il y a 12 jours", "il y a 14 jours", "il y a 15 jours"], texts: ["Campagne claire pour mon profil professionnel, progression régulière.", "Mise en route rapide et suivi sérieux.", "Mon profil ressort mieux dans les recherches.", "Parfait pour travailler mon personal branding.", "Excellent service, accompagnement propre sur plusieurs semaines.", "Progression conforme à ce qui était annoncé.", "Service client réactif et suivi au rendez-vous.", "Bonne progression continue pour ma présence LinkedIn."] },
    faq: { titleBefore: "Vos questions,", titleFocus: "nos réponses", items: [["Comment fonctionne la mise en avant ?", "Nous préparons une campagne de visibilité autour de votre profil LinkedIn et de votre thématique. L'objectif est de présenter votre profil à une audience plus pertinente, avec un rythme progressif et mesuré."], ["Est-ce que je dois vous donner mon mot de passe ?", "Jamais. Nous avons uniquement besoin du lien public de votre profil LinkedIn. Aucun accès au compte n'est demandé."], ["Est-ce que vous agissez sur mon compte ?", "Non. Nous ne nous connectons pas à votre compte et nous ne publions rien à votre place. Le service s'appuie sur une mise en avant externe et progressive."], ["Quand la campagne démarre-t-elle ?", "La préparation démarre après confirmation du paiement. Le déploiement est progressif et peut s'étaler sur plusieurs jours selon le volume choisi."], ["Que se passe-t-il si le volume n'est pas atteint ?", "Notre support vérifie la campagne et peut prolonger la mise en avant sans frais supplémentaires lorsque le volume prévu n'est pas atteint."], ["Est-ce que cela peut aider ma visibilité professionnelle ?", "Oui. Une mise en avant progressive peut soutenir votre présence B2B et donner plus de contexte à vos contenus."]] },
    footer: { desc: "Stratégie de présence en ligne assistée par IA. Campagnes ciblées, suivi clair et progression mesurée.", networks: "Réseaux", help: "Aide", how: "Comment ça marche", support: "Support campagne", tracking: "Suivi de commande", legal: "Légal", legalNotice: "Mentions légales", terms: "CGV", privacy: "Confidentialité", cookies: "Cookies", made: "Made in Paris" },
  },
  en: {
    header: { allNetworks: "All networks", tracking: "Tracking", ratingText: "2,348 reviews", home: "Home" },
    stepper: ["Choose a pack", "Your profile", "Secure payment"],
    step1: { titleBefore: "Targeted LinkedIn visibility", titleFocus: "focused", titleAfter: "and progressive.", volume: "Which volume?", audience: "Followers", included: "included", campaign: "Your campaign", selectedPack: "Selected pack", visibilityPack: "LinkedIn visibility pack", includedCredit: "included credit", total: "Total", discount: "Discount included", continue: "Continue", reassurance: "No commitment - No password - Starts in 1–6 h" },
    step2: { titleBefore: "Which", titleFocus: "profile or page", titleAfter: "would you like to promote?", intro: "Paste your LinkedIn profile or company page link. No password and no account access requested. The profile or page must be public.", usernameLabel: "LinkedIn link (profile or page)", invalidFormat: "Invalid format. Example: linkedin.com/in/your-profile or linkedin.com/company/your-company", notFound: "LinkedIn profile or page not found.", emailLabel: "Your email", emailPlaceholder: "you@example.com", emailHint: "For receipt + order tracking", back: "Back", pay: "Go to payment", errors: { username: "Paste your LinkedIn profile or company page link.", invalid: "Invalid format. Example: linkedin.com/in/your-profile or linkedin.com/company/your-company", email: "Enter your email to receive the receipt.", emailIncomplete: "Is there a typo in your email?" } },
    step3: { titleBefore: "One", titleFocus: "step", titleAfter: "left.", subtitle: "Secure payment - campaign preparation after confirmation.", summary: "Summary", recipient: "Recipient profile", fallbackRecipient: "Your profile", edit: "Edit", visibilityPack: "LinkedIn visibility pack", includedCredit: "included credit", included: "included", campaignCredit: "Campaign credit", free: "FREE", coupon: "Promo code", couponPlaceholder: "PROMO CODE", applied: "Applied", apply: "Apply", saving: "-5% applied - saving", total: "Total incl. tax", securePayment: "Secure payment", legalBefore: "By completing payment, you accept our", legalAfter: "No hidden subscription.", gdpr: "GDPR", backToPacks: "Back to pack selection" },
    why: { eyebrow: "Why Fanovera", title1: "A progressive,", title2: "well-managed", title3: "LinkedIn presence.", items: [["Focused B2B audience", "Our AI helps present your profile to a professional audience aligned with your field."], ["Account protected", "No account access, no posting on your behalf, and no direct action on your profile."], ["No password", "Only your public profile link is needed to prepare the visibility campaign."], ["Follow-up included", "If the planned volume is not reached, our support team reviews and can extend the campaign."]] },
    reviews: { eyebrow: "Customer reviews", rating: "2,348 reviews", dates: ["2 days ago", "7 days ago", "5 days ago", "10 days ago", "5 days ago", "12 days ago", "14 days ago", "15 days ago"], texts: ["Clear campaign for my professional profile, steady progress.", "Fast setup and serious follow-up.", "My profile appears better in searches.", "Perfect for working on my personal branding.", "Excellent service with clean support over several weeks.", "Progress matched what was announced.", "Responsive customer support and reliable follow-up.", "Good continuous progress for my LinkedIn presence."] },
    faq: { titleBefore: "Your questions,", titleFocus: "our answers", items: [["How does the visibility campaign work?", "We prepare a visibility campaign around your LinkedIn profile and topic. The goal is to present your profile to a more relevant audience, with a measured and progressive pace."], ["Do I need to give you my password?", "Never. We only need your public LinkedIn profile link. No account access is requested."], ["Do you act on my account?", "No. We do not log into your account and we do not publish anything on your behalf. The service relies on an external and progressive promotion."], ["When does the campaign start?", "Preparation starts after payment confirmation. Deployment is progressive and can span several days depending on the selected volume."], ["What happens if the volume is not reached?", "Our support team reviews the campaign and can extend the promotion at no extra cost when the planned volume is not reached."], ["Can this help my professional visibility?", "Yes. Progressive promotion can support your B2B presence and give more context to your content."]] },
    footer: { desc: "AI-assisted online presence strategy. Focused campaigns, clear tracking and measured progress.", networks: "Networks", help: "Help", how: "How it works", support: "Campaign support", tracking: "Order tracking", legal: "Legal", legalNotice: "Legal notice", terms: "Terms", privacy: "Privacy", cookies: "Cookies", made: "Made in Paris" },
  },
  es: {
    header: { allNetworks: "Todas las redes", tracking: "Seguimiento", ratingText: "2.348 reseñas", home: "Inicio" },
    stepper: ["Elegir un pack", "Tu perfil", "Pago seguro"],
    step1: { titleBefore: "Visibilidad LinkedIn", titleFocus: "dirigida", titleAfter: "y progresiva.", volume: "¿Qué volumen?", audience: "Seguidores", included: "incluido", campaign: "Tu campaña", selectedPack: "Pack seleccionado", visibilityPack: "Pack de visibilidad LinkedIn", includedCredit: "crédito incluido", total: "Total", discount: "Descuento incluido", continue: "Continuar", reassurance: "Sin compromiso - Sin contraseña - Inicio en 1–6 h" },
    step2: { titleBefore: "¿Qué", titleFocus: "perfil o página", titleAfter: "quieres promocionar?", intro: "Pega el enlace de tu perfil o página de empresa de LinkedIn. Sin contraseña, sin acceso a la cuenta. El perfil o la página debe ser público.", usernameLabel: "Enlace LinkedIn (perfil o página)", invalidFormat: "Formato inválido. Ej: linkedin.com/in/tu-perfil o linkedin.com/company/tu-empresa", notFound: "Perfil o página de LinkedIn no encontrado.", emailLabel: "Tu email", emailPlaceholder: "tu@ejemplo.com", emailHint: "Para el recibo + seguimiento del pedido", back: "Atrás", pay: "Ir al pago", errors: { username: "Pega el enlace de tu perfil o página de empresa de LinkedIn.", invalid: "Formato inválido. Ej: linkedin.com/in/tu-perfil o linkedin.com/company/tu-empresa", email: "Introduce tu email para recibir el recibo.", emailIncomplete: "¿Hay un error en tu email?" } },
    step3: { titleBefore: "Solo un", titleFocus: "paso", titleAfter: "más.", subtitle: "Pago seguro - preparación de la campaña tras la confirmación.", summary: "Resumen", recipient: "Perfil destinatario", fallbackRecipient: "Tu perfil", edit: "Editar", visibilityPack: "Pack de visibilidad LinkedIn", includedCredit: "crédito incluido", included: "incluido", campaignCredit: "Crédito de campaña", free: "GRATIS", coupon: "Código promo", couponPlaceholder: "CÓDIGO PROMO", applied: "Aplicado", apply: "Aplicar", saving: "-5% aplicado - ahorro", total: "Total IVA incl.", securePayment: "Pago seguro", legalBefore: "Al finalizar el pago aceptas nuestros", legalAfter: "Sin suscripción oculta.", gdpr: "RGPD", backToPacks: "Volver a la selección de packs" },
    why: { eyebrow: "Por qué Fanovera", title1: "Una presencia LinkedIn", title2: "progresiva", title3: "y cuidada.", items: [["Audiencia B2B dirigida", "Nuestra IA ayuda a presentar tu perfil a una audiencia profesional coherente con tu sector."], ["Cuenta protegida", "Sin acceso a la cuenta, sin publicaciones en tu nombre, sin acciones directas en tu perfil."], ["Sin contraseña", "Solo el enlace público de tu perfil para preparar la campaña de visibilidad."], ["Seguimiento incluido", "Si no se alcanza el volumen previsto, nuestro soporte revisa y puede prolongar la campaña."]] },
    reviews: { eyebrow: "Reseñas de clientes", rating: "2.348 reseñas", dates: ["hace 2 días", "hace 7 días", "hace 5 días", "hace 10 días", "hace 5 días", "hace 12 días", "hace 14 días", "hace 15 días"], texts: ["Campaña clara para mi perfil profesional, progresión regular.", "Inicio rápido y seguimiento serio.", "Mi perfil aparece mejor en las búsquedas.", "Perfecto para trabajar mi personal branding.", "Excelente servicio, acompañamiento limpio durante varias semanas.", "Progresión conforme a lo anunciado.", "Servicio al cliente reactivo y seguimiento al día.", "Buen progreso continuo para mi presencia en LinkedIn."] },
    faq: { titleBefore: "Tus preguntas,", titleFocus: "nuestras respuestas", items: [["¿Cómo funciona la promoción?", "Preparamos una campaña de visibilidad alrededor de tu perfil de LinkedIn y de tu temática. El objetivo es presentar tu perfil a una audiencia más relevante, con un ritmo progresivo y medido."], ["¿Debo darte mi contraseña?", "Nunca. Solo necesitamos el enlace público de tu perfil de LinkedIn. No se solicita acceso a la cuenta."], ["¿Actúas sobre mi cuenta?", "No. No iniciamos sesión en tu cuenta ni publicamos nada en tu nombre. El servicio se basa en una promoción externa y progresiva."], ["¿Cuándo empieza la campaña?", "La preparación empieza tras la confirmación del pago. El despliegue es progresivo y puede durar varios días según el volumen elegido."], ["¿Qué pasa si no se alcanza el volumen?", "Nuestro soporte revisa la campaña y puede prolongar la promoción sin coste adicional cuando no se alcanza el volumen previsto."], ["¿Puede ayudar a mi visibilidad profesional?", "Sí. Una promoción progresiva puede apoyar tu presencia B2B y dar más contexto a tu contenido."]] },
    footer: { desc: "Estrategia de presencia online asistida por IA. Campañas dirigidas, seguimiento claro y progreso medido.", networks: "Redes", help: "Ayuda", how: "Cómo funciona", support: "Soporte de campaña", tracking: "Seguimiento del pedido", legal: "Legal", legalNotice: "Aviso legal", terms: "Términos", privacy: "Privacidad", cookies: "Cookies", made: "Made in Paris" },
  },
  pt: {
    header: { allNetworks: "Todas as redes", tracking: "Acompanhamento", ratingText: "2.348 avaliações", home: "Início" },
    stepper: ["Escolher um pack", "Seu perfil", "Pagamento seguro"],
    step1: { titleBefore: "Visibilidade LinkedIn", titleFocus: "direcionada", titleAfter: "e progressiva.", volume: "Qual volume?", audience: "Seguidores", included: "incluído", campaign: "Sua campanha", selectedPack: "Pack selecionado", visibilityPack: "Pack de visibilidade LinkedIn", includedCredit: "crédito incluído", total: "Total", discount: "Desconto incluído", continue: "Continuar", reassurance: "Sem compromisso - Sem senha - Início em 1–6 h" },
    step2: { titleBefore: "Qual", titleFocus: "perfil ou página", titleAfter: "deseja promover?", intro: "Cole o link do seu perfil ou da página da empresa no LinkedIn. Sem senha, sem acesso à conta. O perfil ou a página deve ser público.", usernameLabel: "Link LinkedIn (perfil ou página)", invalidFormat: "Formato inválido. Ex: linkedin.com/in/seu-perfil ou linkedin.com/company/sua-empresa", notFound: "Perfil ou página LinkedIn não encontrado.", emailLabel: "Seu email", emailPlaceholder: "voce@exemplo.com", emailHint: "Para o recibo + acompanhamento do pedido", back: "Voltar", pay: "Ir ao pagamento", errors: { username: "Cole o link do seu perfil ou página LinkedIn.", invalid: "Formato inválido. Ex: linkedin.com/in/seu-perfil ou linkedin.com/company/sua-empresa", email: "Digite seu email para receber o recibo.", emailIncomplete: "Há um erro no seu email?" } },
    step3: { titleBefore: "Falta apenas", titleFocus: "um passo", titleAfter: ".", subtitle: "Pagamento seguro - preparação da campanha após confirmação.", summary: "Resumo", recipient: "Perfil destinatário", fallbackRecipient: "Seu perfil", edit: "Editar", visibilityPack: "Pack de visibilidade LinkedIn", includedCredit: "crédito incluído", included: "incluído", campaignCredit: "Crédito de campanha", free: "GRÁTIS", coupon: "Código promocional", couponPlaceholder: "CÓDIGO PROMO", applied: "Aplicado", apply: "Aplicar", saving: "-5% aplicado - economia", total: "Total com impostos", securePayment: "Pagamento seguro", legalBefore: "Ao finalizar o pagamento você aceita nossos", legalAfter: "Sem assinatura oculta.", gdpr: "LGPD", backToPacks: "Voltar à escolha dos packs" },
    why: { eyebrow: "Por que Fanovera", title1: "Uma presença LinkedIn", title2: "progressiva", title3: "e cuidadosa.", items: [["Audiência B2B direcionada", "Nossa IA ajuda a apresentar seu perfil a uma audiência profissional coerente com seu setor."], ["Conta preservada", "Sem acesso à conta, sem publicações em seu nome, sem ações diretas no seu perfil."], ["Sem senha", "Apenas o link público do seu perfil para preparar a campanha de visibilidade."], ["Acompanhamento incluído", "Se o volume previsto não for atingido, nosso suporte revisa e pode estender a campanha."]] },
    reviews: { eyebrow: "Avaliações de clientes", rating: "2.348 avaliações", dates: ["há 2 dias", "há 7 dias", "há 5 dias", "há 10 dias", "há 5 dias", "há 12 dias", "há 14 dias", "há 15 dias"], texts: ["Campanha clara para meu perfil profissional, progresso regular.", "Início rápido e acompanhamento sério.", "Meu perfil aparece melhor nas buscas.", "Perfeito para trabalhar meu personal branding.", "Excelente serviço, acompanhamento limpo durante várias semanas.", "Progresso conforme anunciado.", "Suporte responsivo e acompanhamento pontual.", "Bom progresso contínuo para minha presença no LinkedIn."] },
    faq: { titleBefore: "Suas perguntas,", titleFocus: "nossas respostas", items: [["Como funciona a promoção?", "Preparamos uma campanha de visibilidade em torno do seu perfil LinkedIn e da sua temática. O objetivo é apresentar seu perfil a uma audiência mais relevante, com um ritmo progressivo e medido."], ["Preciso fornecer minha senha?", "Nunca. Precisamos apenas do link público do seu perfil LinkedIn. Nenhum acesso à conta é solicitado."], ["Vocês agem na minha conta?", "Não. Não acessamos sua conta e não publicamos nada em seu nome. O serviço se baseia em uma promoção externa e progressiva."], ["Quando a campanha começa?", "A preparação começa após a confirmação do pagamento. A implantação é progressiva e pode durar vários dias conforme o volume escolhido."], ["O que acontece se o volume não for atingido?", "Nosso suporte revisa a campanha e pode estender a promoção sem custos adicionais quando o volume previsto não é atingido."], ["Isso pode ajudar minha visibilidade profissional?", "Sim. Uma promoção progressiva pode apoiar sua presença B2B e dar mais contexto ao seu conteúdo."]] },
    footer: { desc: "Estratégia de presença online com IA. Campanhas direcionadas, acompanhamento claro e progresso medido.", networks: "Redes", help: "Ajuda", how: "Como funciona", support: "Suporte de campanha", tracking: "Acompanhamento do pedido", legal: "Legal", legalNotice: "Aviso legal", terms: "Termos", privacy: "Privacidade", cookies: "Cookies", made: "Made in Paris" },
  },
  de: {
    header: { allNetworks: "Alle Netzwerke", tracking: "Tracking", ratingText: "2.348 Bewertungen", home: "Startseite" },
    stepper: ["Paket wählen", "Dein Profil", "Sichere Zahlung"],
    step1: { titleBefore: "Gezielte LinkedIn-Sichtbarkeit", titleFocus: "fokussiert", titleAfter: "und progressiv.", volume: "Welches Volumen?", audience: "Follower", included: "inklusive", campaign: "Deine Kampagne", selectedPack: "Ausgewähltes Paket", visibilityPack: "LinkedIn-Sichtbarkeitspaket", includedCredit: "Guthaben inklusive", total: "Gesamt", discount: "Rabatt enthalten", continue: "Weiter", reassurance: "Keine Verpflichtung - Kein Passwort - Start in 1–6 h" },
    step2: { titleBefore: "Welches", titleFocus: "Profil oder welche Seite", titleAfter: "möchtest du bewerben?", intro: "Füge den Link zu deinem LinkedIn-Profil oder zu deiner Unternehmensseite ein. Kein Passwort, kein Kontozugriff. Profil oder Seite müssen öffentlich sein.", usernameLabel: "LinkedIn-Link (Profil oder Seite)", invalidFormat: "Ungültiges Format. Bsp: linkedin.com/in/dein-profil oder linkedin.com/company/dein-unternehmen", notFound: "LinkedIn-Profil oder -Seite nicht gefunden.", emailLabel: "Deine E-Mail", emailPlaceholder: "du@beispiel.com", emailHint: "Für Quittung + Bestellverfolgung", back: "Zurück", pay: "Zur Zahlung", errors: { username: "Füge den Link zu deinem LinkedIn-Profil oder deiner Seite ein.", invalid: "Ungültiges Format. Bsp: linkedin.com/in/dein-profil oder linkedin.com/company/dein-unternehmen", email: "Gib deine E-Mail ein, um die Quittung zu erhalten.", emailIncomplete: "Ist da ein Tippfehler in deiner E-Mail?" } },
    step3: { titleBefore: "Nur noch ein", titleFocus: "Schritt", titleAfter: ".", subtitle: "Sichere Zahlung - Kampagnenvorbereitung nach Bestätigung.", summary: "Zusammenfassung", recipient: "Empfänger-Profil", fallbackRecipient: "Dein Profil", edit: "Bearbeiten", visibilityPack: "LinkedIn-Sichtbarkeitspaket", includedCredit: "Guthaben inklusive", included: "inklusive", campaignCredit: "Kampagnen-Guthaben", free: "GRATIS", coupon: "Promo-Code", couponPlaceholder: "PROMO-CODE", applied: "Angewendet", apply: "Anwenden", saving: "-5% angewendet - Ersparnis", total: "Gesamt inkl. MwSt.", securePayment: "Sichere Zahlung", legalBefore: "Mit Abschluss der Zahlung akzeptierst du unsere", legalAfter: "Kein verstecktes Abonnement.", gdpr: "DSGVO", backToPacks: "Zurück zur Paketauswahl" },
    why: { eyebrow: "Warum Fanovera", title1: "Eine progressive", title2: "gepflegte", title3: "LinkedIn-Präsenz.", items: [["Fokussierte B2B-Zielgruppe", "Unsere KI hilft, dein Profil einer professionellen Zielgruppe zu präsentieren, die zu deiner Branche passt."], ["Konto geschützt", "Kein Kontozugriff, keine Beiträge in deinem Namen, keine direkten Aktionen auf deinem Profil."], ["Kein Passwort", "Nur der öffentliche Link zu deinem Profil wird benötigt, um die Sichtbarkeitskampagne vorzubereiten."], ["Nachverfolgung inklusive", "Wenn das geplante Volumen nicht erreicht wird, prüft und verlängert unser Support die Kampagne."]] },
    reviews: { eyebrow: "Kundenbewertungen", rating: "2.348 Bewertungen", dates: ["vor 2 Tagen", "vor 7 Tagen", "vor 5 Tagen", "vor 10 Tagen", "vor 5 Tagen", "vor 12 Tagen", "vor 14 Tagen", "vor 15 Tagen"], texts: ["Klare Kampagne für mein professionelles Profil, stetiger Fortschritt.", "Schneller Start und seriöse Nachverfolgung.", "Mein Profil erscheint besser in den Suchen.", "Perfekt für meine Personal-Branding-Arbeit.", "Hervorragender Service mit sauberem Support über mehrere Wochen.", "Fortschritt entsprach dem Angekündigten.", "Reaktionsschneller Kundensupport und zuverlässige Nachverfolgung.", "Guter kontinuierlicher Fortschritt für meine LinkedIn-Präsenz."] },
    faq: { titleBefore: "Deine Fragen,", titleFocus: "unsere Antworten", items: [["Wie funktioniert die Sichtbarkeitskampagne?", "Wir bereiten eine Sichtbarkeitskampagne rund um dein LinkedIn-Profil und dein Thema vor. Ziel ist es, dein Profil einer relevanteren Zielgruppe zu präsentieren, mit gemessenem und progressivem Tempo."], ["Muss ich mein Passwort geben?", "Niemals. Wir brauchen nur den öffentlichen Link zu deinem LinkedIn-Profil. Es wird kein Kontozugriff verlangt."], ["Greift ihr auf mein Konto zu?", "Nein. Wir loggen uns nicht in dein Konto ein und veröffentlichen nichts in deinem Namen. Der Service basiert auf einer externen und progressiven Bewerbung."], ["Wann startet die Kampagne?", "Die Vorbereitung beginnt nach Zahlungsbestätigung. Die Bereitstellung ist progressiv und kann je nach gewähltem Volumen mehrere Tage dauern."], ["Was passiert, wenn das Volumen nicht erreicht wird?", "Unser Support prüft die Kampagne und kann die Bewerbung kostenlos verlängern, wenn das geplante Volumen nicht erreicht wird."], ["Kann das meiner professionellen Sichtbarkeit helfen?", "Ja. Eine progressive Bewerbung kann deine B2B-Präsenz unterstützen und deinen Inhalten mehr Kontext geben."]] },
    footer: { desc: "KI-gestützte Online-Präsenzstrategie. Fokussierte Kampagnen, klare Nachverfolgung und gemessener Fortschritt.", networks: "Netzwerke", help: "Hilfe", how: "So funktioniert es", support: "Kampagnensupport", tracking: "Bestellverfolgung", legal: "Rechtliches", legalNotice: "Impressum", terms: "AGB", privacy: "Datenschutz", cookies: "Cookies", made: "Made in Paris" },
  },
  it: {
    header: { allNetworks: "Tutte le reti", tracking: "Monitoraggio", ratingText: "2.348 recensioni", home: "Home" },
    stepper: ["Scegli un pacchetto", "Il tuo profilo", "Pagamento sicuro"],
    step1: { titleBefore: "Visibilità LinkedIn", titleFocus: "mirata", titleAfter: "e progressiva.", volume: "Quale volume?", audience: "Follower", included: "incluso", campaign: "La tua campagna", selectedPack: "Pacchetto selezionato", visibilityPack: "Pacchetto visibilità LinkedIn", includedCredit: "credito incluso", total: "Totale", discount: "Sconto incluso", continue: "Continua", reassurance: "Senza impegno - Senza password - Avvio in 1–6 h" },
    step2: { titleBefore: "Quale", titleFocus: "profilo o pagina", titleAfter: "vuoi promuovere?", intro: "Incolla il link del tuo profilo o della pagina aziendale LinkedIn. Nessuna password, nessun accesso all'account. Il profilo o la pagina deve essere pubblico.", usernameLabel: "Link LinkedIn (profilo o pagina)", invalidFormat: "Formato non valido. Es: linkedin.com/in/il-tuo-profilo o linkedin.com/company/la-tua-azienda", notFound: "Profilo o pagina LinkedIn non trovato.", emailLabel: "La tua email", emailPlaceholder: "tu@esempio.com", emailHint: "Per ricevuta + tracciamento ordine", back: "Indietro", pay: "Vai al pagamento", errors: { username: "Incolla il link del tuo profilo o pagina LinkedIn.", invalid: "Formato non valido. Es: linkedin.com/in/il-tuo-profilo o linkedin.com/company/la-tua-azienda", email: "Inserisci la tua email per ricevere la ricevuta.", emailIncomplete: "C'è un errore nella tua email?" } },
    step3: { titleBefore: "Manca solo", titleFocus: "un passaggio", titleAfter: ".", subtitle: "Pagamento sicuro - preparazione della campagna dopo conferma.", summary: "Riepilogo", recipient: "Profilo destinatario", fallbackRecipient: "Il tuo profilo", edit: "Modifica", visibilityPack: "Pacchetto visibilità LinkedIn", includedCredit: "credito incluso", included: "incluso", campaignCredit: "Credito di campagna", free: "GRATIS", coupon: "Codice promo", couponPlaceholder: "CODICE PROMO", applied: "Applicato", apply: "Applica", saving: "-5% applicato - risparmio", total: "Totale IVA inclusa", securePayment: "Pagamento sicuro", legalBefore: "Completando il pagamento accetti i nostri", legalAfter: "Nessun abbonamento nascosto.", gdpr: "GDPR", backToPacks: "Torna alla scelta dei pacchetti" },
    why: { eyebrow: "Perché Fanovera", title1: "Una presenza LinkedIn", title2: "progressiva", title3: "e curata.", items: [["Audience B2B mirata", "La nostra IA aiuta a presentare il tuo profilo a un'audience professionale coerente con il tuo settore."], ["Account protetto", "Nessun accesso all'account, nessuna pubblicazione al tuo posto, nessuna azione diretta sul tuo profilo."], ["Senza password", "Solo il link pubblico del tuo profilo per preparare la campagna di visibilità."], ["Monitoraggio incluso", "Se il volume previsto non viene raggiunto, il nostro supporto verifica e può prolungare la campagna."]] },
    reviews: { eyebrow: "Recensioni clienti", rating: "2.348 recensioni", dates: ["2 giorni fa", "7 giorni fa", "5 giorni fa", "10 giorni fa", "5 giorni fa", "12 giorni fa", "14 giorni fa", "15 giorni fa"], texts: ["Campagna chiara per il mio profilo professionale, progresso regolare.", "Avvio rapido e monitoraggio serio.", "Il mio profilo appare meglio nelle ricerche.", "Perfetto per lavorare sul mio personal branding.", "Servizio eccellente, supporto pulito per diverse settimane.", "Progresso conforme a quanto annunciato.", "Servizio clienti reattivo e monitoraggio puntuale.", "Buon progresso continuo per la mia presenza LinkedIn."] },
    faq: { titleBefore: "Le tue domande,", titleFocus: "le nostre risposte", items: [["Come funziona la promozione?", "Prepariamo una campagna di visibilità intorno al tuo profilo LinkedIn e alla tua tematica. L'obiettivo è presentare il tuo profilo a un'audience più rilevante, con un ritmo progressivo e misurato."], ["Devo darti la mia password?", "Mai. Abbiamo solo bisogno del link pubblico del tuo profilo LinkedIn. Nessun accesso all'account viene richiesto."], ["Agite sul mio account?", "No. Non accediamo al tuo account e non pubblichiamo nulla al tuo posto. Il servizio si basa su una promozione esterna e progressiva."], ["Quando inizia la campagna?", "La preparazione inizia dopo la conferma del pagamento. La distribuzione è progressiva e può durare diversi giorni a seconda del volume scelto."], ["Cosa succede se il volume non viene raggiunto?", "Il nostro supporto verifica la campagna e può prolungare la promozione senza costi aggiuntivi quando il volume previsto non viene raggiunto."], ["Questo può aiutare la mia visibilità professionale?", "Sì. Una promozione progressiva può supportare la tua presenza B2B e dare più contesto ai tuoi contenuti."]] },
    footer: { desc: "Strategia di presenza online assistita da IA. Campagne mirate, monitoraggio chiaro e progresso misurato.", networks: "Reti", help: "Aiuto", how: "Come funziona", support: "Supporto campagna", tracking: "Monitoraggio ordine", legal: "Legale", legalNotice: "Note legali", terms: "Termini", privacy: "Privacy", cookies: "Cookies", made: "Made in Paris" },
  },
  tr: {
    header: { allNetworks: "Tüm ağlar", tracking: "Takip", ratingText: "2.348 yorum", home: "Anasayfa" },
    stepper: ["Paket seç", "Profiliniz", "Güvenli ödeme"],
    step1: { titleBefore: "Hedefli LinkedIn görünürlüğü", titleFocus: "odaklı", titleAfter: "ve aşamalı.", volume: "Hangi hacim?", audience: "Takipçiler", included: "dahil", campaign: "Kampanyanız", selectedPack: "Seçili paket", visibilityPack: "LinkedIn görünürlük paketi", includedCredit: "kredi dahil", total: "Toplam", discount: "İndirim dahil", continue: "Devam", reassurance: "Taahhütsüz - Şifresiz - 1–6 saatte başlar" },
    step2: { titleBefore: "Hangi", titleFocus: "profili veya sayfayı", titleAfter: "tanıtmak istiyorsunuz?", intro: "LinkedIn profil veya şirket sayfası bağlantınızı yapıştırın. Şifre yok, hesap erişimi yok. Profil veya sayfa herkese açık olmalı.", usernameLabel: "LinkedIn bağlantısı (profil veya sayfa)", invalidFormat: "Geçersiz format. Örn: linkedin.com/in/profil-adiniz veya linkedin.com/company/sirketiniz", notFound: "LinkedIn profili veya sayfası bulunamadı.", emailLabel: "E-postanız", emailPlaceholder: "siz@ornek.com", emailHint: "Makbuz + sipariş takibi için", back: "Geri", pay: "Ödemeye git", errors: { username: "LinkedIn profil veya sayfa bağlantınızı yapıştırın.", invalid: "Geçersiz format. Örn: linkedin.com/in/profil-adiniz veya linkedin.com/company/sirketiniz", email: "Makbuzu almak için e-postanızı girin.", emailIncomplete: "E-postanızda bir hata mı var?" } },
    step3: { titleBefore: "Sadece bir", titleFocus: "adım", titleAfter: "kaldı.", subtitle: "Güvenli ödeme - onaydan sonra kampanya hazırlığı.", summary: "Özet", recipient: "Alıcı profil", fallbackRecipient: "Profiliniz", edit: "Düzenle", visibilityPack: "LinkedIn görünürlük paketi", includedCredit: "kredi dahil", included: "dahil", campaignCredit: "Kampanya kredisi", free: "ÜCRETSİZ", coupon: "Promosyon kodu", couponPlaceholder: "PROMO KODU", applied: "Uygulandı", apply: "Uygula", saving: "-5% uygulandı - tasarruf", total: "KDV dahil toplam", securePayment: "Güvenli ödeme", legalBefore: "Ödemeyi tamamlayarak kabul ediyorsunuz:", legalAfter: "Gizli abonelik yok.", gdpr: "KVKK", backToPacks: "Paket seçimine dön" },
    why: { eyebrow: "Neden Fanovera", title1: "Aşamalı bir LinkedIn", title2: "varlığı", title3: "özenle yönetilen.", items: [["Odaklı B2B kitle", "AI'mız profilinizi sektörünüze uygun profesyonel bir kitleye sunmaya yardımcı olur."], ["Hesap korunur", "Hesap erişimi yok, sizin adınıza paylaşım yok, profilinizde doğrudan eylem yok."], ["Şifresiz", "Görünürlük kampanyasını hazırlamak için sadece profilinizin herkese açık bağlantısı gerekli."], ["Takip dahil", "Planlanan hacme ulaşılmazsa, destek ekibimiz kampanyayı inceler ve uzatabilir."]] },
    reviews: { eyebrow: "Müşteri yorumları", rating: "2.348 yorum", dates: ["2 gün önce", "7 gün önce", "5 gün önce", "10 gün önce", "5 gün önce", "12 gün önce", "14 gün önce", "15 gün önce"], texts: ["Profesyonel profilim için net kampanya, istikrarlı ilerleme.", "Hızlı başlangıç ve ciddi takip.", "Profilim aramalarda daha iyi görünüyor.", "Kişisel marka çalışmam için mükemmel.", "Mükemmel hizmet, haftalar boyunca temiz destek.", "İlerleme duyurulduğu gibi.", "Duyarlı müşteri desteği ve güvenilir takip.", "LinkedIn varlığım için iyi sürekli ilerleme."] },
    faq: { titleBefore: "Sorularınız,", titleFocus: "cevaplarımız", items: [["Görünürlük kampanyası nasıl çalışır?", "LinkedIn profiliniz ve konunuz etrafında bir görünürlük kampanyası hazırlıyoruz. Amaç, profilinizi daha alakalı bir kitleye sunmak, ölçülü ve aşamalı bir ritimle."], ["Şifremi vermem gerekiyor mu?", "Asla. Sadece LinkedIn profilinizin herkese açık bağlantısına ihtiyacımız var. Hesap erişimi talep edilmez."], ["Hesabımda işlem yapıyor musunuz?", "Hayır. Hesabınıza giriş yapmıyoruz ve sizin adınıza hiçbir şey yayınlamıyoruz. Hizmet, harici ve aşamalı bir tanıtıma dayanır."], ["Kampanya ne zaman başlar?", "Hazırlık ödeme onayından sonra başlar. Dağıtım aşamalıdır ve seçilen hacme göre birkaç gün sürebilir."], ["Hacme ulaşılmazsa ne olur?", "Destek ekibimiz kampanyayı inceler ve planlanan hacme ulaşılmadığında tanıtımı ek ücret ödemeden uzatabilir."], ["Bu profesyonel görünürlüğüme yardımcı olabilir mi?", "Evet. Aşamalı bir tanıtım, B2B varlığınızı destekleyebilir ve içeriklerinize daha fazla bağlam verebilir."]] },
    footer: { desc: "AI destekli online varlık stratejisi. Odaklı kampanyalar, net takip ve ölçülü ilerleme.", networks: "Ağlar", help: "Yardım", how: "Nasıl çalışır", support: "Kampanya desteği", tracking: "Sipariş takibi", legal: "Yasal", legalNotice: "Yasal bilgiler", terms: "Şartlar", privacy: "Gizlilik", cookies: "Çerezler", made: "Made in Paris" },
  },
};

type LinkedinCopy = (typeof copy)[keyof typeof copy];

const localized: Record<SupportedLocale, LinkedinCopy> = {
  fr: copy.fr,
  en: copy.en,
  es: copy.es,
  pt: copy.pt,
  de: copy.de,
  it: copy.it,
  tr: copy.tr,
};

export function useLinkedinCopy() {
  const { locale } = useI18n();
  const { mode, surfaceMode } = useMarketingMode();
  const base = applyPerformanceProductCopy(localized[locale] || copy.fr, {
    locale,
    mode,
    product: "LinkedIn",
    audience: "Audience",
  });
  return appendNoCommitmentFaq(applyBlackhatProductCopy(base, surfaceMode, { locale, product: "LinkedIn", audience: "Connections" }), locale);
}
