import { useI18n } from "../i18n/I18nProvider";
import { deepTranslateCopy } from "../i18n/deepTranslate";
import type { SupportedLocale } from "../i18n/types";

const copy = {
  fr: {
    header: { allNetworks: "Tous les reseaux", tracking: "Suivi", ratingText: "2 348 avis", home: "Accueil" },
    stepper: ["Choisir un pack", "Votre chaine", "Paiement securise"],
    step1: { titleBefore: "Une visibilite Twitch", titleFocus: "ciblee", titleAfter: "& progressive.", volume: "Quel volume ?", audience: "Audience", included: "inclus", campaign: "Votre campagne", selectedPack: "Pack selectionne", visibilityPack: "Pack visibilite Twitch", includedCredit: "credit inclus", total: "Total", discount: "Remise incluse", continue: "Continuer", reassurance: "Sans engagement - Aucun mot de passe demande" },
    step2: { titleBefore: "Quelle", titleFocus: "chaine", titleAfter: "souhaitez-vous promouvoir ?", intro: "Entrez votre nom de chaine Twitch. Aucun mot de passe, aucun acces demande. La chaine doit etre publique.", usernameLabel: "Nom de votre chaine Twitch", usernamePlaceholder: "votrechaine", invalidFormat: "Format invalide. 4-25 caracteres : lettres, chiffres, \"_\" uniquement.", notFound: "Chaine Twitch introuvable.", emailLabel: "Votre e-mail (pour le recu)", emailPlaceholder: "vous@exemple.com", emailHint: "On vous envoie uniquement votre facture. Pas de spam, jamais.", back: "Retour", pay: "Aller au paiement", bioUnavailable: "Bio non disponible", fallbackChannel: "votrechaine", errors: { username: "Entrez votre nom de chaine Twitch.", invalid: "Format invalide. 4-25 caracteres : lettres, chiffres, \"_\".", checking: "Verification de la chaine en cours...", notFound: "Cette chaine est introuvable sur Twitch.", generic: "Chaine non trouvee.", email: "Entrez votre e-mail pour recevoir le recu." } },
    step3: { titleBefore: "Plus qu'une", titleFocus: "etape", titleAfter: ".", subtitle: "Paiement securise - preparation de la campagne apres confirmation.", summary: "Recapitulatif", recipient: "Chaine destinataire", fallbackRecipient: "Votre chaine", edit: "Modifier", visibilityPack: "Pack visibilite Twitch", includedCredit: "credit inclus", campaignCredit: "Credit de campagne", free: "OFFERT", coupon: "Code promo", couponPlaceholder: "CODE PROMO", applied: "Applique", apply: "Appliquer", saving: "-5% applique - economie", total: "Total TTC", securePayment: "Paiement securise", legalBefore: "En finalisant le paiement vous acceptez nos", legalAfter: "Aucun abonnement cache.", gdpr: "RGPD", backToPacks: "Retour au choix des packs" },
    why: { eyebrow: "Pourquoi Fanovera", title1: "Une presence Twitch", title2: "progressive", title3: "et soignee.", items: [["Audience ciblee", "Notre IA aide a presenter votre chaine Twitch a une audience coherente avec votre niche."], ["Compte preserve", "Aucun acces au compte, aucune publication a votre place, aucune action directe sur votre chaine."], ["Sans mot de passe", "Juste votre nom de chaine public pour preparer la campagne de visibilite."], ["Suivi inclus", "Si le volume prevu n'est pas atteint, notre support verifie et peut prolonger la campagne."]] },
    reviews: { eyebrow: "Avis clients", rating: "2 348 avis", dates: ["il y a 2 jours", "il y a 7 jours", "il y a 5 jours", "il y a 10 jours", "il y a 5 jours", "il y a 12 jours", "il y a 14 jours", "il y a 15 jours"], texts: ["Campagne lancee rapidement, premiers signaux en moins de 48h.", "Progression reguliere pour ma chaine Twitch.", "Croissance progressive sur plusieurs semaines, rien d'agressif.", "Premiere campagne Twitch, service serieux et suivi clair.", "Excellent service, accompagnement propre sur plusieurs semaines.", "Rien a redire, progression conforme a ce qui etait annonce.", "Service client reactif et suivi au rendez-vous.", "Ma chaine ressort mieux dans les recommandations."] },
    faq: { titleBefore: "Vos questions,", titleFocus: "nos reponses", items: [["Comment fonctionne la mise en avant ?", "Nous preparons une campagne de visibilite autour de votre chaine Twitch et de votre thematique. L'objectif est de presenter votre contenu a une audience plus pertinente, avec un rythme progressif et mesure."], ["Est-ce que je dois vous donner mon mot de passe ?", "Jamais. Nous avons uniquement besoin de votre nom de chaine Twitch public. Aucun acces au compte n'est demande."], ["Est-ce que vous agissez sur mon compte ?", "Non. Nous ne nous connectons pas a votre compte et nous ne publions rien a votre place. Le service s'appuie sur une mise en avant externe et progressive."], ["Quand la campagne demarre-t-elle ?", "La preparation demarre apres confirmation du paiement. Le deploiement est progressif et peut s'etaler sur plusieurs jours selon le volume choisi."], ["Que se passe-t-il si le volume n'est pas atteint ?", "Notre support verifie la campagne et peut prolonger la mise en avant sans frais supplementaires lorsque le volume prevu n'est pas atteint."], ["Cela peut-il aider ma chaine Twitch ?", "Oui. Une campagne progressive peut renforcer les signaux de traction autour de votre chaine, en complement de votre contenu et de votre regularite de stream."]] },
    footer: { desc: "Strategie de presence en ligne assistee par IA. Campagnes ciblees, suivi clair et progression mesuree.", networks: "Reseaux", help: "Aide", how: "Comment ca marche", support: "Support campagne", tracking: "Suivi de commande", legal: "Legal", legalNotice: "Mentions legales", terms: "CGV", privacy: "Confidentialite", cookies: "Cookies", made: "Made in Paris" },
  },
  en: {
    header: { allNetworks: "All networks", tracking: "Tracking", ratingText: "2,348 reviews", home: "Home" },
    stepper: ["Choose a pack", "Your channel", "Secure payment"],
    step1: { titleBefore: "Targeted Twitch visibility", titleFocus: "focused", titleAfter: "and progressive.", volume: "Which volume?", audience: "Audience", included: "included", campaign: "Your campaign", selectedPack: "Selected pack", visibilityPack: "Twitch visibility pack", includedCredit: "included credit", total: "Total", discount: "Discount included", continue: "Continue", reassurance: "No commitment - No password required" },
    step2: { titleBefore: "Which", titleFocus: "channel", titleAfter: "would you like to promote?", intro: "Enter your Twitch channel name. No password and no account access requested. The channel must be public.", usernameLabel: "Your Twitch channel name", usernamePlaceholder: "yourchannel", invalidFormat: "Invalid format. 4-25 characters: letters, numbers, \"_\" only.", notFound: "Twitch channel not found.", emailLabel: "Your email (for the receipt)", emailPlaceholder: "you@example.com", emailHint: "We only send your invoice. No spam, ever.", back: "Back", pay: "Go to payment", bioUnavailable: "Bio unavailable", fallbackChannel: "yourchannel", errors: { username: "Enter your Twitch channel name.", invalid: "Invalid format. 4-25 characters: letters, numbers, \"_\".", checking: "Channel verification in progress...", notFound: "This channel cannot be found on Twitch.", generic: "Channel not found.", email: "Enter your email to receive the receipt." } },
    step3: { titleBefore: "One", titleFocus: "step", titleAfter: "left.", subtitle: "Secure payment - campaign preparation after confirmation.", summary: "Summary", recipient: "Recipient channel", fallbackRecipient: "Your channel", edit: "Edit", visibilityPack: "Twitch visibility pack", includedCredit: "included credit", campaignCredit: "Campaign credit", free: "FREE", coupon: "Promo code", couponPlaceholder: "PROMO CODE", applied: "Applied", apply: "Apply", saving: "-5% applied - saving", total: "Total incl. tax", securePayment: "Secure payment", legalBefore: "By completing payment, you accept our", legalAfter: "No hidden subscription.", gdpr: "GDPR", backToPacks: "Back to pack selection" },
    why: { eyebrow: "Why Fanovera", title1: "A progressive,", title2: "well-managed", title3: "Twitch presence.", items: [["Focused audience", "Our AI helps present your Twitch channel to an audience aligned with your niche."], ["Account protected", "No account access, no posting on your behalf, and no direct action on your channel."], ["No password", "Only your public channel name is needed to prepare the visibility campaign."], ["Follow-up included", "If the planned volume is not reached, our support team reviews and can extend the campaign."]] },
    reviews: { eyebrow: "Customer reviews", rating: "2,348 reviews", dates: ["2 days ago", "7 days ago", "5 days ago", "10 days ago", "5 days ago", "12 days ago", "14 days ago", "15 days ago"], texts: ["Campaign launched quickly, first signals in under 48h.", "Steady progress for my Twitch channel.", "Progressive growth over several weeks, nothing aggressive.", "First Twitch campaign, serious service and clear tracking.", "Excellent service with clean support over several weeks.", "Nothing to add, progress matched what was announced.", "Responsive support and reliable follow-up.", "My channel appears better in recommendations."] },
    faq: { titleBefore: "Your questions,", titleFocus: "our answers", items: [["How does the visibility campaign work?", "We prepare a visibility campaign around your Twitch channel and topic. The goal is to present your content to a more relevant audience, with a measured and progressive pace."], ["Do I need to give you my password?", "Never. We only need your public Twitch channel name. No account access is requested."], ["Do you act on my account?", "No. We do not log into your account and we do not publish anything on your behalf. The service relies on an external and progressive promotion."], ["When does the campaign start?", "Preparation starts after payment confirmation. Deployment is progressive and can span several days depending on the selected volume."], ["What happens if the volume is not reached?", "Our support team reviews the campaign and can extend the promotion at no extra cost when the planned volume is not reached."], ["Can this help my Twitch channel?", "Yes. A progressive campaign can support traction signals around your channel, alongside your content and stream consistency."]] },
    footer: { desc: "AI-assisted online presence strategy. Focused campaigns, clear tracking and measured progress.", networks: "Networks", help: "Help", how: "How it works", support: "Campaign support", tracking: "Order tracking", legal: "Legal", legalNotice: "Legal notice", terms: "Terms", privacy: "Privacy", cookies: "Cookies", made: "Made in Paris" },
  },
} as const;

type TwitchCopy = (typeof copy)[keyof typeof copy];

const localized: Record<SupportedLocale, TwitchCopy> = {
  fr: copy.fr,
  en: copy.en,
  es: deepTranslateCopy(copy.fr, "es"),
  pt: deepTranslateCopy(copy.fr, "pt"),
  de: deepTranslateCopy(copy.fr, "de"),
  it: deepTranslateCopy(copy.fr, "it"),
  tr: deepTranslateCopy(copy.fr, "tr"),
};

export function useTwitchCopy() {
  const { locale } = useI18n();
  return localized[locale] || copy.fr;
}
