import { useI18n } from "../i18n/I18nProvider";
import type { SupportedLocale } from "../i18n/types";
import { applyPerformanceProductCopy, applyBlackhatProductCopy } from "../lib/performanceCopy";
import { useMarketingMode } from "../marketing/MarketingModeProvider";

const copy = {
  fr: {
    header: { allNetworks: "Tous les réseaux", tracking: "Suivi", ratingText: "2 348 avis", home: "Accueil" },
    stepper: ["Choisir un pack", "Votre chaîne", "Paiement sécurisé"],
    step1: { titleBefore: "Une visibilité Twitch", titleFocus: "ciblée", titleAfter: "& progressive.", volume: "Quel volume ?", audience: "Abonnés", included: "inclus", campaign: "Votre campagne", selectedPack: "Pack sélectionné", visibilityPack: "Pack visibilité Twitch", includedCredit: "crédit inclus", total: "Total", discount: "Remise incluse", continue: "Continuer", reassurance: "Sans engagement - Aucun mot de passe - Démarrage sous 1–6 h" },
    step2: { titleBefore: "Quelle", titleFocus: "chaîne", titleAfter: "souhaitez-vous promouvoir ?", intro: "Entrez votre nom de chaîne Twitch. Aucun mot de passe, aucun accès demandé. La chaîne doit être publique.", usernameLabel: "Nom de votre chaîne Twitch", usernamePlaceholder: "votrechaine", invalidFormat: "Format invalide. 4-25 caractères : lettres, chiffres, \"_\" uniquement.", notFound: "Chaîne Twitch introuvable.", emailLabel: "Votre e-mail (pour le reçu)", emailPlaceholder: "vous@exemple.com", emailHint: "On vous envoie uniquement votre facture. Pas de spam, jamais.", back: "Retour", pay: "Aller au paiement", bioUnavailable: "Bio non disponible", fallbackChannel: "votrechaine", errors: { username: "Entrez votre nom de chaîne Twitch.", invalid: "Format invalide. 4-25 caractères : lettres, chiffres, \"_\".", checking: "Vérification de la chaîne en cours...", notFound: "Cette chaîne est introuvable sur Twitch.", generic: "Chaîne non trouvée.", email: "Entrez votre e-mail pour recevoir le reçu." } },
    step3: { titleBefore: "Plus qu'une", titleFocus: "étape", titleAfter: ".", subtitle: "Paiement sécurisé - préparation de la campagne après confirmation.", summary: "Récapitulatif", recipient: "Chaîne destinataire", fallbackRecipient: "Votre chaîne", edit: "Modifier", visibilityPack: "Pack visibilité Twitch", includedCredit: "crédit inclus", included: "inclus", campaignCredit: "Crédit de campagne", free: "OFFERT", coupon: "Code promo", couponPlaceholder: "CODE PROMO", applied: "Appliqué", apply: "Appliquer", saving: "-5% appliqué - économie", total: "Total TTC", securePayment: "Paiement sécurisé", legalBefore: "En finalisant le paiement vous acceptez nos", legalAfter: "Aucun abonnement caché.", gdpr: "RGPD", backToPacks: "Retour au choix des packs" },
    why: { eyebrow: "Pourquoi Fanovera", title1: "Une présence Twitch", title2: "progressive", title3: "et soignée.", items: [["Audience ciblée", "Notre IA aide à présenter votre chaîne Twitch à une audience cohérente avec votre niche."], ["Compte préservé", "Aucun accès au compte, aucune publication à votre place, aucune action directe sur votre chaîne."], ["Sans mot de passe", "Juste votre nom de chaîne public pour préparer la campagne de visibilité."], ["Suivi inclus", "Si le volume prévu n'est pas atteint, notre support vérifie et peut prolonger la campagne."]] },
    reviews: { eyebrow: "Avis clients", rating: "2 348 avis", dates: ["il y a 2 jours", "il y a 7 jours", "il y a 5 jours", "il y a 10 jours", "il y a 5 jours", "il y a 12 jours", "il y a 14 jours", "il y a 15 jours"], texts: ["Campagne lancée rapidement, premiers signaux en moins de 48h.", "Progression régulière pour ma chaîne Twitch.", "Croissance progressive sur plusieurs semaines, rien d'agressif.", "Première campagne Twitch, service sérieux et suivi clair.", "Excellent service, accompagnement propre sur plusieurs semaines.", "Rien à redire, progression conforme à ce qui était annoncé.", "Service client réactif et suivi au rendez-vous.", "Ma chaîne ressort mieux dans les recommandations."] },
    faq: { titleBefore: "Vos questions,", titleFocus: "nos réponses", items: [["Comment fonctionne la mise en avant ?", "Nous préparons une campagne de visibilité autour de votre chaîne Twitch et de votre thématique. L'objectif est de présenter votre contenu à une audience plus pertinente, avec un rythme progressif et mesuré."], ["Est-ce que je dois vous donner mon mot de passe ?", "Jamais. Nous avons uniquement besoin de votre nom de chaîne Twitch public. Aucun accès au compte n'est demandé."], ["Est-ce que vous agissez sur mon compte ?", "Non. Nous ne nous connectons pas à votre compte et nous ne publions rien à votre place. Le service s'appuie sur une mise en avant externe et progressive."], ["Quand la campagne démarre-t-elle ?", "La préparation démarre après confirmation du paiement. Le déploiement est progressif et peut s'étaler sur plusieurs jours selon le volume choisi."], ["Que se passe-t-il si le volume n'est pas atteint ?", "Notre support vérifie la campagne et peut prolonger la mise en avant sans frais supplémentaires lorsque le volume prévu n'est pas atteint."], ["Cela peut-il aider ma chaîne Twitch ?", "Oui. Une campagne progressive peut renforcer les signaux de traction autour de votre chaîne, en complément de votre contenu et de votre régularité de stream."]] },
    footer: { desc: "Stratégie de présence en ligne assistée par IA. Campagnes ciblées, suivi clair et progression mesurée.", networks: "Réseaux", help: "Aide", how: "Comment ça marche", support: "Support campagne", tracking: "Suivi de commande", legal: "Légal", legalNotice: "Mentions légales", terms: "CGV", privacy: "Confidentialité", cookies: "Cookies", made: "Made in Paris" },
  },
  en: {
    header: { allNetworks: "All networks", tracking: "Tracking", ratingText: "2,348 reviews", home: "Home" },
    stepper: ["Choose a pack", "Your channel", "Secure payment"],
    step1: { titleBefore: "Targeted Twitch visibility", titleFocus: "focused", titleAfter: "and progressive.", volume: "Which volume?", audience: "Followers", included: "included", campaign: "Your campaign", selectedPack: "Selected pack", visibilityPack: "Twitch visibility pack", includedCredit: "included credit", total: "Total", discount: "Discount included", continue: "Continue", reassurance: "No commitment - No password - Starts in 1–6 h" },
    step2: { titleBefore: "Which", titleFocus: "channel", titleAfter: "would you like to promote?", intro: "Enter your Twitch channel name. No password and no account access requested. The channel must be public.", usernameLabel: "Your Twitch channel name", usernamePlaceholder: "yourchannel", invalidFormat: "Invalid format. 4-25 characters: letters, numbers, \"_\" only.", notFound: "Twitch channel not found.", emailLabel: "Your email (for the receipt)", emailPlaceholder: "you@example.com", emailHint: "We only send your invoice. No spam, ever.", back: "Back", pay: "Go to payment", bioUnavailable: "Bio unavailable", fallbackChannel: "yourchannel", errors: { username: "Enter your Twitch channel name.", invalid: "Invalid format. 4-25 characters: letters, numbers, \"_\".", checking: "Channel verification in progress...", notFound: "This channel cannot be found on Twitch.", generic: "Channel not found.", email: "Enter your email to receive the receipt." } },
    step3: { titleBefore: "One", titleFocus: "step", titleAfter: "left.", subtitle: "Secure payment - campaign preparation after confirmation.", summary: "Summary", recipient: "Recipient channel", fallbackRecipient: "Your channel", edit: "Edit", visibilityPack: "Twitch visibility pack", includedCredit: "included credit", included: "included", campaignCredit: "Campaign credit", free: "FREE", coupon: "Promo code", couponPlaceholder: "PROMO CODE", applied: "Applied", apply: "Apply", saving: "-5% applied - saving", total: "Total incl. tax", securePayment: "Secure payment", legalBefore: "By completing payment, you accept our", legalAfter: "No hidden subscription.", gdpr: "GDPR", backToPacks: "Back to pack selection" },
    why: { eyebrow: "Why Fanovera", title1: "A progressive,", title2: "well-managed", title3: "Twitch presence.", items: [["Focused audience", "Our AI helps present your Twitch channel to an audience aligned with your niche."], ["Account protected", "No account access, no posting on your behalf, and no direct action on your channel."], ["No password", "Only your public channel name is needed to prepare the visibility campaign."], ["Follow-up included", "If the planned volume is not reached, our support team reviews and can extend the campaign."]] },
    reviews: { eyebrow: "Customer reviews", rating: "2,348 reviews", dates: ["2 days ago", "7 days ago", "5 days ago", "10 days ago", "5 days ago", "12 days ago", "14 days ago", "15 days ago"], texts: ["Campaign launched quickly, first signals in under 48h.", "Steady progress for my Twitch channel.", "Progressive growth over several weeks, nothing aggressive.", "First Twitch campaign, serious service and clear tracking.", "Excellent service with clean support over several weeks.", "Nothing to add, progress matched what was announced.", "Responsive support and reliable follow-up.", "My channel appears better in recommendations."] },
    faq: { titleBefore: "Your questions,", titleFocus: "our answers", items: [["How does the visibility campaign work?", "We prepare a visibility campaign around your Twitch channel and topic. The goal is to present your content to a more relevant audience, with a measured and progressive pace."], ["Do I need to give you my password?", "Never. We only need your public Twitch channel name. No account access is requested."], ["Do you act on my account?", "No. We do not log into your account and we do not publish anything on your behalf. The service relies on an external and progressive promotion."], ["When does the campaign start?", "Preparation starts after payment confirmation. Deployment is progressive and can span several days depending on the selected volume."], ["What happens if the volume is not reached?", "Our support team reviews the campaign and can extend the promotion at no extra cost when the planned volume is not reached."], ["Can this help my Twitch channel?", "Yes. A progressive campaign can support traction signals around your channel, alongside your content and stream consistency."]] },
    footer: { desc: "AI-assisted online presence strategy. Focused campaigns, clear tracking and measured progress.", networks: "Networks", help: "Help", how: "How it works", support: "Campaign support", tracking: "Order tracking", legal: "Legal", legalNotice: "Legal notice", terms: "Terms", privacy: "Privacy", cookies: "Cookies", made: "Made in Paris" },
  },
  es: {
    header: { allNetworks: "Todas las redes", tracking: "Seguimiento", ratingText: "2.348 reseñas", home: "Inicio" },
    stepper: ["Elegir un pack", "Tu canal", "Pago seguro"],
    step1: { titleBefore: "Visibilidad Twitch", titleFocus: "dirigida", titleAfter: "y progresiva.", volume: "¿Qué volumen?", audience: "Seguidores", included: "incluido", campaign: "Tu campaña", selectedPack: "Pack seleccionado", visibilityPack: "Pack de visibilidad Twitch", includedCredit: "crédito incluido", total: "Total", discount: "Descuento incluido", continue: "Continuar", reassurance: "Sin compromiso - Sin contraseña - Inicio en 1–6 h" },
    step2: { titleBefore: "¿Qué", titleFocus: "canal", titleAfter: "quieres promocionar?", intro: "Introduce el nombre de tu canal de Twitch. Sin contraseña, sin acceso a la cuenta. El canal debe ser público.", usernameLabel: "Nombre de tu canal de Twitch", usernamePlaceholder: "tucanal", invalidFormat: "Formato inválido. 4-25 caracteres: letras, números, \"_\".", notFound: "Canal de Twitch no encontrado.", emailLabel: "Tu email (para el recibo)", emailPlaceholder: "tu@ejemplo.com", emailHint: "Solo enviamos tu factura. Nunca spam.", back: "Atrás", pay: "Ir al pago", bioUnavailable: "Bio no disponible", fallbackChannel: "tucanal", errors: { username: "Introduce el nombre de tu canal de Twitch.", invalid: "Formato inválido. 4-25 caracteres: letras, números, \"_\".", checking: "Verificación del canal en curso...", notFound: "Este canal no se encuentra en Twitch.", generic: "Canal no encontrado.", email: "Introduce tu email para recibir el recibo." } },
    step3: { titleBefore: "Solo un", titleFocus: "paso", titleAfter: "más.", subtitle: "Pago seguro - preparación de la campaña tras la confirmación.", summary: "Resumen", recipient: "Canal destinatario", fallbackRecipient: "Tu canal", edit: "Editar", visibilityPack: "Pack de visibilidad Twitch", includedCredit: "crédito incluido", included: "incluido", campaignCredit: "Crédito de campaña", free: "GRATIS", coupon: "Código promo", couponPlaceholder: "CÓDIGO PROMO", applied: "Aplicado", apply: "Aplicar", saving: "-5% aplicado - ahorro", total: "Total IVA incl.", securePayment: "Pago seguro", legalBefore: "Al finalizar el pago aceptas nuestros", legalAfter: "Sin suscripción oculta.", gdpr: "RGPD", backToPacks: "Volver a la selección de packs" },
    why: { eyebrow: "Por qué Fanovera", title1: "Una presencia Twitch", title2: "progresiva", title3: "y cuidada.", items: [["Audiencia dirigida", "Nuestra IA ayuda a presentar tu canal de Twitch a una audiencia coherente con tu nicho."], ["Cuenta protegida", "Sin acceso a la cuenta, sin publicaciones en tu nombre, sin acciones directas en tu canal."], ["Sin contraseña", "Solo el nombre público de tu canal para preparar la campaña de visibilidad."], ["Seguimiento incluido", "Si no se alcanza el volumen previsto, nuestro soporte revisa y puede prolongar la campaña."]] },
    reviews: { eyebrow: "Reseñas de clientes", rating: "2.348 reseñas", dates: ["hace 2 días", "hace 7 días", "hace 5 días", "hace 10 días", "hace 5 días", "hace 12 días", "hace 14 días", "hace 15 días"], texts: ["Campaña lanzada rápido, primeras señales en menos de 48h.", "Progresión regular para mi canal de Twitch.", "Crecimiento progresivo durante varias semanas, nada agresivo.", "Primera campaña Twitch, servicio serio y seguimiento claro.", "Excelente servicio, acompañamiento limpio durante varias semanas.", "Nada que decir, progreso conforme a lo anunciado.", "Servicio al cliente reactivo y seguimiento al día.", "Mi canal aparece mejor en las recomendaciones."] },
    faq: { titleBefore: "Tus preguntas,", titleFocus: "nuestras respuestas", items: [["¿Cómo funciona la promoción?", "Preparamos una campaña de visibilidad alrededor de tu canal de Twitch y de tu temática. El objetivo es presentar tu contenido a una audiencia más relevante, con un ritmo progresivo y medido."], ["¿Debo darte mi contraseña?", "Nunca. Solo necesitamos el nombre público de tu canal de Twitch. No se solicita acceso a la cuenta."], ["¿Actúas sobre mi cuenta?", "No. No iniciamos sesión en tu cuenta ni publicamos nada en tu nombre. El servicio se basa en una promoción externa y progresiva."], ["¿Cuándo empieza la campaña?", "La preparación empieza tras la confirmación del pago. El despliegue es progresivo y puede durar varios días según el volumen elegido."], ["¿Qué pasa si no se alcanza el volumen?", "Nuestro soporte revisa la campaña y puede prolongar la promoción sin coste adicional cuando no se alcanza el volumen previsto."], ["¿Esto puede ayudar a mi canal de Twitch?", "Sí. Una campaña progresiva puede reforzar las señales de tracción alrededor de tu canal, complementando tu contenido y la regularidad de tus directos."]] },
    footer: { desc: "Estrategia de presencia online asistida por IA. Campañas dirigidas, seguimiento claro y progreso medido.", networks: "Redes", help: "Ayuda", how: "Cómo funciona", support: "Soporte de campaña", tracking: "Seguimiento del pedido", legal: "Legal", legalNotice: "Aviso legal", terms: "Términos", privacy: "Privacidad", cookies: "Cookies", made: "Made in Paris" },
  },
  pt: {
    header: { allNetworks: "Todas as redes", tracking: "Acompanhamento", ratingText: "2.348 avaliações", home: "Início" },
    stepper: ["Escolher um pack", "Seu canal", "Pagamento seguro"],
    step1: { titleBefore: "Visibilidade Twitch", titleFocus: "direcionada", titleAfter: "e progressiva.", volume: "Qual volume?", audience: "Seguidores", included: "incluído", campaign: "Sua campanha", selectedPack: "Pack selecionado", visibilityPack: "Pack de visibilidade Twitch", includedCredit: "crédito incluído", total: "Total", discount: "Desconto incluído", continue: "Continuar", reassurance: "Sem compromisso - Sem senha - Início em 1–6 h" },
    step2: { titleBefore: "Qual", titleFocus: "canal", titleAfter: "deseja promover?", intro: "Digite o nome do seu canal da Twitch. Sem senha, sem acesso à conta. O canal deve ser público.", usernameLabel: "Nome do seu canal da Twitch", usernamePlaceholder: "seucanal", invalidFormat: "Formato inválido. 4-25 caracteres: letras, números, \"_\".", notFound: "Canal da Twitch não encontrado.", emailLabel: "Seu email (para o recibo)", emailPlaceholder: "voce@exemplo.com", emailHint: "Enviamos apenas sua nota. Nunca spam.", back: "Voltar", pay: "Ir ao pagamento", bioUnavailable: "Bio indisponível", fallbackChannel: "seucanal", errors: { username: "Digite o nome do seu canal da Twitch.", invalid: "Formato inválido. 4-25 caracteres: letras, números, \"_\".", checking: "Verificação do canal em andamento...", notFound: "Não encontramos este canal na Twitch.", generic: "Canal não encontrado.", email: "Digite seu email para receber o recibo." } },
    step3: { titleBefore: "Falta apenas", titleFocus: "um passo", titleAfter: ".", subtitle: "Pagamento seguro - preparação da campanha após confirmação.", summary: "Resumo", recipient: "Canal destinatário", fallbackRecipient: "Seu canal", edit: "Editar", visibilityPack: "Pack de visibilidade Twitch", includedCredit: "crédito incluído", included: "incluído", campaignCredit: "Crédito de campanha", free: "GRÁTIS", coupon: "Código promocional", couponPlaceholder: "CÓDIGO PROMO", applied: "Aplicado", apply: "Aplicar", saving: "-5% aplicado - economia", total: "Total com impostos", securePayment: "Pagamento seguro", legalBefore: "Ao finalizar o pagamento você aceita nossos", legalAfter: "Sem assinatura oculta.", gdpr: "LGPD", backToPacks: "Voltar à escolha dos packs" },
    why: { eyebrow: "Por que Fanovera", title1: "Uma presença Twitch", title2: "progressiva", title3: "e cuidadosa.", items: [["Audiência direcionada", "Nossa IA ajuda a apresentar seu canal da Twitch a uma audiência coerente com seu nicho."], ["Conta preservada", "Sem acesso à conta, sem publicações em seu nome, sem ações diretas no seu canal."], ["Sem senha", "Apenas o nome público do seu canal para preparar a campanha de visibilidade."], ["Acompanhamento incluído", "Se o volume previsto não for atingido, nosso suporte revisa e pode estender a campanha."]] },
    reviews: { eyebrow: "Avaliações de clientes", rating: "2.348 avaliações", dates: ["há 2 dias", "há 7 dias", "há 5 dias", "há 10 dias", "há 5 dias", "há 12 dias", "há 14 dias", "há 15 dias"], texts: ["Campanha lançada rapidamente, primeiros sinais em menos de 48h.", "Progresso regular para meu canal da Twitch.", "Crescimento progressivo em várias semanas, nada agressivo.", "Primeira campanha Twitch, serviço sério e acompanhamento claro.", "Excelente serviço, acompanhamento limpo por várias semanas.", "Nada a dizer, progresso conforme anunciado.", "Suporte responsivo e acompanhamento pontual.", "Meu canal aparece melhor nas recomendações."] },
    faq: { titleBefore: "Suas perguntas,", titleFocus: "nossas respostas", items: [["Como funciona a promoção?", "Preparamos uma campanha de visibilidade em torno do seu canal da Twitch e da sua temática. O objetivo é apresentar seu conteúdo a uma audiência mais relevante, com um ritmo progressivo e medido."], ["Preciso fornecer minha senha?", "Nunca. Precisamos apenas do nome público do seu canal da Twitch. Nenhum acesso à conta é solicitado."], ["Vocês agem na minha conta?", "Não. Não acessamos sua conta e não publicamos nada em seu nome. O serviço se baseia em uma promoção externa e progressiva."], ["Quando a campanha começa?", "A preparação começa após a confirmação do pagamento. A implantação é progressiva e pode durar vários dias conforme o volume escolhido."], ["O que acontece se o volume não for atingido?", "Nosso suporte revisa a campanha e pode estender a promoção sem custos adicionais quando o volume previsto não é atingido."], ["Isso pode ajudar meu canal da Twitch?", "Sim. Uma campanha progressiva pode reforçar os sinais de tração em torno do seu canal, complementando seu conteúdo e a regularidade das suas lives."]] },
    footer: { desc: "Estratégia de presença online com IA. Campanhas direcionadas, acompanhamento claro e progresso medido.", networks: "Redes", help: "Ajuda", how: "Como funciona", support: "Suporte de campanha", tracking: "Acompanhamento do pedido", legal: "Legal", legalNotice: "Aviso legal", terms: "Termos", privacy: "Privacidade", cookies: "Cookies", made: "Made in Paris" },
  },
  de: {
    header: { allNetworks: "Alle Netzwerke", tracking: "Tracking", ratingText: "2.348 Bewertungen", home: "Startseite" },
    stepper: ["Paket wählen", "Dein Kanal", "Sichere Zahlung"],
    step1: { titleBefore: "Gezielte Twitch-Sichtbarkeit", titleFocus: "fokussiert", titleAfter: "und progressiv.", volume: "Welches Volumen?", audience: "Follower", included: "inklusive", campaign: "Deine Kampagne", selectedPack: "Ausgewähltes Paket", visibilityPack: "Twitch-Sichtbarkeitspaket", includedCredit: "Guthaben inklusive", total: "Gesamt", discount: "Rabatt enthalten", continue: "Weiter", reassurance: "Keine Verpflichtung - Kein Passwort - Start in 1–6 h" },
    step2: { titleBefore: "Welchen", titleFocus: "Kanal", titleAfter: "möchtest du bewerben?", intro: "Gib den Namen deines Twitch-Kanals ein. Kein Passwort, kein Kontozugriff. Der Kanal muss öffentlich sein.", usernameLabel: "Name deines Twitch-Kanals", usernamePlaceholder: "deinkanal", invalidFormat: "Ungültiges Format. 4-25 Zeichen: Buchstaben, Zahlen, \"_\".", notFound: "Twitch-Kanal nicht gefunden.", emailLabel: "Deine E-Mail (für die Quittung)", emailPlaceholder: "du@beispiel.com", emailHint: "Wir senden nur deine Rechnung. Niemals Spam.", back: "Zurück", pay: "Zur Zahlung", bioUnavailable: "Bio nicht verfügbar", fallbackChannel: "deinkanal", errors: { username: "Gib den Namen deines Twitch-Kanals ein.", invalid: "Ungültiges Format. 4-25 Zeichen: Buchstaben, Zahlen, \"_\".", checking: "Kanalprüfung läuft...", notFound: "Dieser Kanal kann auf Twitch nicht gefunden werden.", generic: "Kanal nicht gefunden.", email: "Gib deine E-Mail ein, um die Quittung zu erhalten." } },
    step3: { titleBefore: "Nur noch ein", titleFocus: "Schritt", titleAfter: ".", subtitle: "Sichere Zahlung - Kampagnenvorbereitung nach Bestätigung.", summary: "Zusammenfassung", recipient: "Empfänger-Kanal", fallbackRecipient: "Dein Kanal", edit: "Bearbeiten", visibilityPack: "Twitch-Sichtbarkeitspaket", includedCredit: "Guthaben inklusive", included: "inklusive", campaignCredit: "Kampagnen-Guthaben", free: "GRATIS", coupon: "Promo-Code", couponPlaceholder: "PROMO-CODE", applied: "Angewendet", apply: "Anwenden", saving: "-5% angewendet - Ersparnis", total: "Gesamt inkl. MwSt.", securePayment: "Sichere Zahlung", legalBefore: "Mit Abschluss der Zahlung akzeptierst du unsere", legalAfter: "Kein verstecktes Abonnement.", gdpr: "DSGVO", backToPacks: "Zurück zur Paketauswahl" },
    why: { eyebrow: "Warum Fanovera", title1: "Eine progressive", title2: "gepflegte", title3: "Twitch-Präsenz.", items: [["Fokussierte Zielgruppe", "Unsere KI hilft, deinen Twitch-Kanal einer Zielgruppe zu präsentieren, die zu deiner Nische passt."], ["Konto geschützt", "Kein Kontozugriff, keine Beiträge in deinem Namen, keine direkten Aktionen auf deinem Kanal."], ["Kein Passwort", "Nur dein öffentlicher Kanalname wird benötigt, um die Sichtbarkeitskampagne vorzubereiten."], ["Nachverfolgung inklusive", "Wenn das geplante Volumen nicht erreicht wird, prüft und verlängert unser Support die Kampagne."]] },
    reviews: { eyebrow: "Kundenbewertungen", rating: "2.348 Bewertungen", dates: ["vor 2 Tagen", "vor 7 Tagen", "vor 5 Tagen", "vor 10 Tagen", "vor 5 Tagen", "vor 12 Tagen", "vor 14 Tagen", "vor 15 Tagen"], texts: ["Kampagne schnell gestartet, erste Signale unter 48 Std.", "Stetiger Fortschritt für meinen Twitch-Kanal.", "Progressives Wachstum über mehrere Wochen, nichts Aggressives.", "Erste Twitch-Kampagne, seriöser Service und klare Nachverfolgung.", "Hervorragender Service mit sauberem Support über mehrere Wochen.", "Nichts hinzuzufügen, Fortschritt entsprach dem Angekündigten.", "Reaktionsschneller Support und zuverlässige Nachverfolgung.", "Mein Kanal erscheint besser in den Empfehlungen."] },
    faq: { titleBefore: "Deine Fragen,", titleFocus: "unsere Antworten", items: [["Wie funktioniert die Sichtbarkeitskampagne?", "Wir bereiten eine Sichtbarkeitskampagne rund um deinen Twitch-Kanal und dein Thema vor. Ziel ist es, deine Inhalte einer relevanteren Zielgruppe zu präsentieren, mit gemessenem und progressivem Tempo."], ["Muss ich mein Passwort geben?", "Niemals. Wir brauchen nur deinen öffentlichen Twitch-Kanalnamen. Es wird kein Kontozugriff verlangt."], ["Greift ihr auf mein Konto zu?", "Nein. Wir loggen uns nicht in dein Konto ein und veröffentlichen nichts in deinem Namen. Der Service basiert auf einer externen und progressiven Bewerbung."], ["Wann startet die Kampagne?", "Die Vorbereitung beginnt nach Zahlungsbestätigung. Die Bereitstellung ist progressiv und kann je nach gewähltem Volumen mehrere Tage dauern."], ["Was passiert, wenn das Volumen nicht erreicht wird?", "Unser Support prüft die Kampagne und kann die Bewerbung kostenlos verlängern, wenn das geplante Volumen nicht erreicht wird."], ["Kann das meinem Twitch-Kanal helfen?", "Ja. Eine progressive Kampagne kann die Traktionssignale rund um deinen Kanal verstärken, ergänzend zu deinem Inhalt und deiner Stream-Regelmäßigkeit."]] },
    footer: { desc: "KI-gestützte Online-Präsenzstrategie. Fokussierte Kampagnen, klare Nachverfolgung und gemessener Fortschritt.", networks: "Netzwerke", help: "Hilfe", how: "So funktioniert es", support: "Kampagnensupport", tracking: "Bestellverfolgung", legal: "Rechtliches", legalNotice: "Impressum", terms: "AGB", privacy: "Datenschutz", cookies: "Cookies", made: "Made in Paris" },
  },
  it: {
    header: { allNetworks: "Tutte le reti", tracking: "Monitoraggio", ratingText: "2.348 recensioni", home: "Home" },
    stepper: ["Scegli un pacchetto", "Il tuo canale", "Pagamento sicuro"],
    step1: { titleBefore: "Visibilità Twitch", titleFocus: "mirata", titleAfter: "e progressiva.", volume: "Quale volume?", audience: "Follower", included: "incluso", campaign: "La tua campagna", selectedPack: "Pacchetto selezionato", visibilityPack: "Pacchetto visibilità Twitch", includedCredit: "credito incluso", total: "Totale", discount: "Sconto incluso", continue: "Continua", reassurance: "Senza impegno - Senza password - Avvio in 1–6 h" },
    step2: { titleBefore: "Quale", titleFocus: "canale", titleAfter: "vuoi promuovere?", intro: "Inserisci il nome del tuo canale Twitch. Nessuna password, nessun accesso all'account. Il canale deve essere pubblico.", usernameLabel: "Nome del tuo canale Twitch", usernamePlaceholder: "iltuocanale", invalidFormat: "Formato non valido. 4-25 caratteri: lettere, numeri, \"_\".", notFound: "Canale Twitch non trovato.", emailLabel: "La tua email (per la ricevuta)", emailPlaceholder: "tu@esempio.com", emailHint: "Inviamo solo la tua fattura. Mai spam.", back: "Indietro", pay: "Vai al pagamento", bioUnavailable: "Bio non disponibile", fallbackChannel: "iltuocanale", errors: { username: "Inserisci il nome del tuo canale Twitch.", invalid: "Formato non valido. 4-25 caratteri: lettere, numeri, \"_\".", checking: "Verifica del canale in corso...", notFound: "Non troviamo questo canale su Twitch.", generic: "Canale non trovato.", email: "Inserisci la tua email per ricevere la ricevuta." } },
    step3: { titleBefore: "Manca solo", titleFocus: "un passaggio", titleAfter: ".", subtitle: "Pagamento sicuro - preparazione della campagna dopo conferma.", summary: "Riepilogo", recipient: "Canale destinatario", fallbackRecipient: "Il tuo canale", edit: "Modifica", visibilityPack: "Pacchetto visibilità Twitch", includedCredit: "credito incluso", included: "incluso", campaignCredit: "Credito di campagna", free: "GRATIS", coupon: "Codice promo", couponPlaceholder: "CODICE PROMO", applied: "Applicato", apply: "Applica", saving: "-5% applicato - risparmio", total: "Totale IVA inclusa", securePayment: "Pagamento sicuro", legalBefore: "Completando il pagamento accetti i nostri", legalAfter: "Nessun abbonamento nascosto.", gdpr: "GDPR", backToPacks: "Torna alla scelta dei pacchetti" },
    why: { eyebrow: "Perché Fanovera", title1: "Una presenza Twitch", title2: "progressiva", title3: "e curata.", items: [["Audience mirata", "La nostra IA aiuta a presentare il tuo canale Twitch a un'audience coerente con la tua nicchia."], ["Account protetto", "Nessun accesso all'account, nessuna pubblicazione al tuo posto, nessuna azione diretta sul tuo canale."], ["Senza password", "Solo il nome pubblico del tuo canale per preparare la campagna di visibilità."], ["Monitoraggio incluso", "Se il volume previsto non viene raggiunto, il nostro supporto verifica e può prolungare la campagna."]] },
    reviews: { eyebrow: "Recensioni clienti", rating: "2.348 recensioni", dates: ["2 giorni fa", "7 giorni fa", "5 giorni fa", "10 giorni fa", "5 giorni fa", "12 giorni fa", "14 giorni fa", "15 giorni fa"], texts: ["Campagna avviata rapidamente, primi segnali in meno di 48h.", "Progresso costante per il mio canale Twitch.", "Crescita progressiva su diverse settimane, niente di aggressivo.", "Prima campagna Twitch, servizio serio e monitoraggio chiaro.", "Servizio eccellente, supporto pulito per diverse settimane.", "Niente da dire, progresso conforme a quanto annunciato.", "Supporto reattivo e monitoraggio puntuale.", "Il mio canale appare meglio nelle raccomandazioni."] },
    faq: { titleBefore: "Le tue domande,", titleFocus: "le nostre risposte", items: [["Come funziona la promozione?", "Prepariamo una campagna di visibilità intorno al tuo canale Twitch e alla tua tematica. L'obiettivo è presentare il tuo contenuto a un'audience più rilevante, con un ritmo progressivo e misurato."], ["Devo darti la mia password?", "Mai. Abbiamo solo bisogno del nome pubblico del tuo canale Twitch. Nessun accesso all'account viene richiesto."], ["Agite sul mio account?", "No. Non accediamo al tuo account e non pubblichiamo nulla al tuo posto. Il servizio si basa su una promozione esterna e progressiva."], ["Quando inizia la campagna?", "La preparazione inizia dopo la conferma del pagamento. La distribuzione è progressiva e può durare diversi giorni a seconda del volume scelto."], ["Cosa succede se il volume non viene raggiunto?", "Il nostro supporto verifica la campagna e può prolungare la promozione senza costi aggiuntivi quando il volume previsto non viene raggiunto."], ["Questo può aiutare il mio canale Twitch?", "Sì. Una campagna progressiva può rafforzare i segnali di trazione intorno al tuo canale, in complemento al tuo contenuto e alla regolarità delle tue dirette."]] },
    footer: { desc: "Strategia di presenza online assistita da IA. Campagne mirate, monitoraggio chiaro e progresso misurato.", networks: "Reti", help: "Aiuto", how: "Come funziona", support: "Supporto campagna", tracking: "Monitoraggio ordine", legal: "Legale", legalNotice: "Note legali", terms: "Termini", privacy: "Privacy", cookies: "Cookies", made: "Made in Paris" },
  },
  tr: {
    header: { allNetworks: "Tüm ağlar", tracking: "Takip", ratingText: "2.348 yorum", home: "Anasayfa" },
    stepper: ["Paket seç", "Kanalınız", "Güvenli ödeme"],
    step1: { titleBefore: "Hedefli Twitch görünürlüğü", titleFocus: "odaklı", titleAfter: "ve aşamalı.", volume: "Hangi hacim?", audience: "Takipçiler", included: "dahil", campaign: "Kampanyanız", selectedPack: "Seçili paket", visibilityPack: "Twitch görünürlük paketi", includedCredit: "kredi dahil", total: "Toplam", discount: "İndirim dahil", continue: "Devam", reassurance: "Taahhütsüz - Şifresiz - 1–6 saatte başlar" },
    step2: { titleBefore: "Hangi", titleFocus: "kanalı", titleAfter: "tanıtmak istiyorsunuz?", intro: "Twitch kanal adınızı girin. Şifre yok, hesap erişimi yok. Kanal herkese açık olmalı.", usernameLabel: "Twitch kanal adınız", usernamePlaceholder: "kanaliniz", invalidFormat: "Geçersiz format. 4-25 karakter: harf, rakam, \"_\".", notFound: "Twitch kanalı bulunamadı.", emailLabel: "E-postanız (makbuz için)", emailPlaceholder: "siz@ornek.com", emailHint: "Sadece faturanızı gönderiyoruz. Asla spam yok.", back: "Geri", pay: "Ödemeye git", bioUnavailable: "Bio mevcut değil", fallbackChannel: "kanaliniz", errors: { username: "Twitch kanal adınızı girin.", invalid: "Geçersiz format. 4-25 karakter: harf, rakam, \"_\".", checking: "Kanal doğrulaması devam ediyor...", notFound: "Bu kanal Twitch'te bulunamıyor.", generic: "Kanal bulunamadı.", email: "Makbuzu almak için e-postanızı girin." } },
    step3: { titleBefore: "Sadece bir", titleFocus: "adım", titleAfter: "kaldı.", subtitle: "Güvenli ödeme - onaydan sonra kampanya hazırlığı.", summary: "Özet", recipient: "Alıcı kanal", fallbackRecipient: "Kanalınız", edit: "Düzenle", visibilityPack: "Twitch görünürlük paketi", includedCredit: "kredi dahil", included: "dahil", campaignCredit: "Kampanya kredisi", free: "ÜCRETSİZ", coupon: "Promosyon kodu", couponPlaceholder: "PROMO KODU", applied: "Uygulandı", apply: "Uygula", saving: "-5% uygulandı - tasarruf", total: "KDV dahil toplam", securePayment: "Güvenli ödeme", legalBefore: "Ödemeyi tamamlayarak kabul ediyorsunuz:", legalAfter: "Gizli abonelik yok.", gdpr: "KVKK", backToPacks: "Paket seçimine dön" },
    why: { eyebrow: "Neden Fanovera", title1: "Aşamalı bir Twitch", title2: "varlığı", title3: "özenle yönetilen.", items: [["Odaklı kitle", "AI'mız Twitch kanalınızı nişinize uygun bir kitleye sunmaya yardımcı olur."], ["Hesap korunur", "Hesap erişimi yok, sizin adınıza paylaşım yok, kanalınızda doğrudan eylem yok."], ["Şifresiz", "Görünürlük kampanyasını hazırlamak için sadece herkese açık kanal adınız gerekli."], ["Takip dahil", "Planlanan hacme ulaşılmazsa, destek ekibimiz kampanyayı inceler ve uzatabilir."]] },
    reviews: { eyebrow: "Müşteri yorumları", rating: "2.348 yorum", dates: ["2 gün önce", "7 gün önce", "5 gün önce", "10 gün önce", "5 gün önce", "12 gün önce", "14 gün önce", "15 gün önce"], texts: ["Kampanya hızlı başlatıldı, ilk sinyaller 48 saatten kısa sürede.", "Twitch kanalım için istikrarlı ilerleme.", "Birkaç hafta boyunca aşamalı büyüme, agresif değil.", "İlk Twitch kampanyam, ciddi hizmet ve net takip.", "Mükemmel hizmet, haftalar boyunca temiz destek.", "Söylenecek bir şey yok, ilerleme duyurulduğu gibi.", "Duyarlı destek ve güvenilir takip.", "Kanalım önerilerde daha iyi görünüyor."] },
    faq: { titleBefore: "Sorularınız,", titleFocus: "cevaplarımız", items: [["Görünürlük kampanyası nasıl çalışır?", "Twitch kanalınız ve konunuz etrafında bir görünürlük kampanyası hazırlıyoruz. Amaç, içeriğinizi daha alakalı bir kitleye sunmak, ölçülü ve aşamalı bir ritimle."], ["Şifremi vermem gerekiyor mu?", "Asla. Sadece herkese açık Twitch kanal adınıza ihtiyacımız var. Hesap erişimi talep edilmez."], ["Hesabımda işlem yapıyor musunuz?", "Hayır. Hesabınıza giriş yapmıyoruz ve sizin adınıza hiçbir şey yayınlamıyoruz. Hizmet, harici ve aşamalı bir tanıtıma dayanır."], ["Kampanya ne zaman başlar?", "Hazırlık ödeme onayından sonra başlar. Dağıtım aşamalıdır ve seçilen hacme göre birkaç gün sürebilir."], ["Hacme ulaşılmazsa ne olur?", "Destek ekibimiz kampanyayı inceler ve planlanan hacme ulaşılmadığında tanıtımı ek ücret ödemeden uzatabilir."], ["Bu Twitch kanalıma yardım edebilir mi?", "Evet. Aşamalı bir kampanya, içeriğinizi ve yayın düzeninizi tamamlayarak kanalınız etrafındaki çekim sinyallerini güçlendirebilir."]] },
    footer: { desc: "AI destekli online varlık stratejisi. Odaklı kampanyalar, net takip ve ölçülü ilerleme.", networks: "Ağlar", help: "Yardım", how: "Nasıl çalışır", support: "Kampanya desteği", tracking: "Sipariş takibi", legal: "Yasal", legalNotice: "Yasal bilgiler", terms: "Şartlar", privacy: "Gizlilik", cookies: "Çerezler", made: "Made in Paris" },
  },
} as const;

type TwitchCopy = (typeof copy)[keyof typeof copy];

const localized: Record<SupportedLocale, TwitchCopy> = {
  fr: copy.fr,
  en: copy.en,
  es: copy.es,
  pt: copy.pt,
  de: copy.de,
  it: copy.it,
  tr: copy.tr,
};

export function useTwitchCopy() {
  const { locale } = useI18n();
  const { mode, surfaceMode } = useMarketingMode();
  const base = applyPerformanceProductCopy(localized[locale] || copy.fr, {
    locale,
    mode,
    product: "Twitch",
    audience: "Audience",
  });
  return applyBlackhatProductCopy(base, surfaceMode, { locale, product: "Twitch", audience: "Viewers" });
}
