import { useI18n } from "../i18n/I18nProvider";
import { deepTranslateCopy } from "../i18n/deepTranslate";
import type { SupportedLocale } from "../i18n/types";

function translateLocalCopy<T>(source: T, locale: SupportedLocale): T {
  const translated = locale === "en" ? deepTranslateCopy(source, locale) : source;
  if (locale === "fr" || locale === "en") return translated;

  const replacements: Record<Exclude<SupportedLocale, "fr" | "en">, Array<[string, string]>> = {
    es: [["Tous les reseaux", "Todas las redes"], ["Paiement securise", "Pago seguro"], ["Choisir un pack", "Elegir un pack"], ["Votre profil", "Tu perfil"], ["Une visibilite X", "Visibilidad en X"], ["ciblee", "dirigida"], ["& progressive.", "y progresiva."], ["Quel volume ?", "Que volumen?"], ["Abonnes", "Seguidores"], ["Votre campagne", "Tu campana"], ["Pack selectionne", "Pack seleccionado"], ["Pack visibilite X", "Pack de visibilidad X"], ["credit inclus", "credito incluido"], ["Remise incluse", "Descuento incluido"], ["Continuer", "Continuar"], ["Sans engagement", "Sin compromiso"], ["Aucun mot de passe demande", "Sin contrasena"], ["Quel", "Que"], ["profil", "perfil"], ["souhaitez-vous promouvoir ?", "quieres promocionar?"], ["Abonnements", "Siguiendo"], ["Popularite", "Popularidad"], ["Nouveau total", "Nuevo total"], ["Recapitulatif", "Resumen"], ["Profil destinataire", "Perfil destinatario"], ["Plus qu'une", "Solo queda una"], ["etape", "etapa"], ["preparation de la campagne apres confirmation", "preparacion de la campana tras la confirmacion"], ["Pourquoi Fanovera", "Por que Fanovera"], ["Des abonnes X", "Seguidores de X"], ["progressifs", "progresivos"], ["et soignes.", "y cuidados."], ["Avis clients", "Opiniones de clientes"], ["Vos questions,", "Tus preguntas,"], ["nos reponses", "nuestras respuestas"]],
    pt: [["Tous les reseaux", "Todas as redes"], ["Paiement securise", "Pagamento seguro"], ["Choisir un pack", "Escolher um pacote"], ["Votre profil", "Seu perfil"], ["Une visibilite X", "Visibilidade no X"], ["ciblee", "segmentada"], ["& progressive.", "e progressiva."], ["Quel volume ?", "Qual volume?"], ["Abonnes", "Seguidores"], ["Votre campagne", "Sua campanha"], ["Pack selectionne", "Pacote selecionado"], ["Pack visibilite X", "Pacote de visibilidade X"], ["credit inclus", "credito incluido"], ["Remise incluse", "Desconto incluido"], ["Continuer", "Continuar"], ["Sans engagement", "Sem compromisso"], ["Aucun mot de passe demande", "Sem senha"], ["Quel", "Qual"], ["profil", "perfil"], ["souhaitez-vous promouvoir ?", "quer promover?"], ["Abonnements", "Seguindo"], ["Popularite", "Popularidade"], ["Nouveau total", "Novo total"], ["Recapitulatif", "Resumo"], ["Profil destinataire", "Perfil destinatario"], ["Plus qu'une", "So falta uma"], ["etape", "etapa"], ["preparation de la campagne apres confirmation", "preparacao da campanha apos confirmacao"], ["Pourquoi Fanovera", "Por que Fanovera"], ["Des abonnes X", "Seguidores no X"], ["progressifs", "progressivos"], ["et soignes.", "e cuidados."], ["Avis clients", "Avaliacoes de clientes"], ["Vos questions,", "Suas perguntas,"], ["nos reponses", "nossas respostas"]],
    de: [["Tous les reseaux", "Alle Netzwerke"], ["Paiement securise", "Sichere Zahlung"], ["Choisir un pack", "Paket wahlen"], ["Votre profil", "Dein Profil"], ["Une visibilite X", "X-Sichtbarkeit"], ["ciblee", "gezielt"], ["& progressive.", "und progressiv."], ["Quel volume ?", "Welches Volumen?"], ["Abonnes", "Follower"], ["Votre campagne", "Deine Kampagne"], ["Pack selectionne", "Ausgewahltes Paket"], ["Pack visibilite X", "X-Sichtbarkeitspaket"], ["credit inclus", "inklusive Guthaben"], ["Remise incluse", "Rabatt enthalten"], ["Continuer", "Weiter"], ["Sans engagement", "Ohne Bindung"], ["Aucun mot de passe demande", "Kein Passwort erforderlich"], ["Quel", "Welches"], ["profil", "Profil"], ["souhaitez-vous promouvoir ?", "mochtest du bewerben?"], ["Abonnements", "Folgt"], ["Popularite", "Beliebtheit"], ["Nouveau total", "Neue Summe"], ["Recapitulatif", "Zusammenfassung"], ["Profil destinataire", "Zielprofil"], ["Plus qu'une", "Nur noch ein"], ["etape", "Schritt"], ["preparation de la campagne apres confirmation", "Kampagnenvorbereitung nach Bestatigung"], ["Pourquoi Fanovera", "Warum Fanovera"], ["Des abonnes X", "X-Follower"], ["progressifs", "progressiv"], ["et soignes.", "und sorgfaltig."], ["Avis clients", "Kundenbewertungen"], ["Vos questions,", "Deine Fragen,"], ["nos reponses", "unsere Antworten"]],
    it: [["Tous les reseaux", "Tutte le reti"], ["Paiement securise", "Pagamento sicuro"], ["Choisir un pack", "Scegli un pacchetto"], ["Votre profil", "Il tuo profilo"], ["Une visibilite X", "Visibilita X"], ["ciblee", "mirata"], ["& progressive.", "e progressiva."], ["Quel volume ?", "Quale volume?"], ["Abonnes", "Follower"], ["Votre campagne", "La tua campagna"], ["Pack selectionne", "Pacchetto selezionato"], ["Pack visibilite X", "Pacchetto visibilita X"], ["credit inclus", "credito incluso"], ["Remise incluse", "Sconto incluso"], ["Continuer", "Continua"], ["Sans engagement", "Senza impegno"], ["Aucun mot de passe demande", "Nessuna password richiesta"], ["Quel", "Quale"], ["profil", "profilo"], ["souhaitez-vous promouvoir ?", "vuoi promuovere?"], ["Abonnements", "Seguiti"], ["Popularite", "Popolarita"], ["Nouveau total", "Nuovo totale"], ["Recapitulatif", "Riepilogo"], ["Profil destinataire", "Profilo destinatario"], ["Plus qu'une", "Manca solo un"], ["etape", "passaggio"], ["preparation de la campagne apres confirmation", "preparazione della campagna dopo conferma"], ["Pourquoi Fanovera", "Perche Fanovera"], ["Des abonnes X", "Follower X"], ["progressifs", "progressivi"], ["et soignes.", "e curati."], ["Avis clients", "Recensioni clienti"], ["Vos questions,", "Le tue domande,"], ["nos reponses", "le nostre risposte"]],
    tr: [["Tous les reseaux", "Tum aglar"], ["Paiement securise", "Guvenli odeme"], ["Choisir un pack", "Paket sec"], ["Votre profil", "Profiliniz"], ["Une visibilite X", "X gorunurlugu"], ["ciblee", "hedefli"], ["& progressive.", "ve kademeli."], ["Quel volume ?", "Hangi hacim?"], ["Abonnes", "Takipciler"], ["Votre campagne", "Kampanyaniz"], ["Pack selectionne", "Secilen paket"], ["Pack visibilite X", "X gorunurluk paketi"], ["credit inclus", "dahil kredi"], ["Remise incluse", "Indirim dahil"], ["Continuer", "Devam et"], ["Sans engagement", "Taahhutsuz"], ["Aucun mot de passe demande", "Sifre gerekmez"], ["Quel", "Hangi"], ["profil", "profil"], ["souhaitez-vous promouvoir ?", "one cikarilsin?"], ["Abonnements", "Takip edilen"], ["Popularite", "Populerlik"], ["Nouveau total", "Yeni toplam"], ["Recapitulatif", "Ozet"], ["Profil destinataire", "Hedef profil"], ["Plus qu'une", "Sadece bir"], ["etape", "adim kaldi"], ["preparation de la campagne apres confirmation", "onaydan sonra kampanya hazirligi"], ["Pourquoi Fanovera", "Neden Fanovera"], ["Des abonnes X", "X takipcileri"], ["progressifs", "kademeli"], ["et soignes.", "ve ozenli."], ["Avis clients", "Musteri yorumlari"], ["Vos questions,", "Sorulariniz,"], ["nos reponses", "cevaplarimiz"]],
  };

  const walk = (value: unknown): unknown => {
    if (typeof value === "string") return replacements[locale].reduce((text, [from, to]) => text.replaceAll(from, to), value);
    if (Array.isArray(value)) return value.map(walk);
    if (value && typeof value === "object") return Object.fromEntries(Object.entries(value).map(([key, val]) => [key, walk(val)]));
    return value;
  };

  return walk(translated) as T;
}

const copy = {
  fr: {
    header: { allNetworks: "Tous les réseaux", tracking: "Suivi", ratingText: "2 348 avis", home: "Accueil" },
    stepper: ["Choisir un pack", "Votre profil", "Paiement sécurisé"],
    step1: {
      titleBefore: "Une visibilité X", titleFocus: "ciblée", titleAfter: "& progressive.", volume: "Quel volume ?", audience: "Abonnés", included: "inclus", campaign: "Votre campagne", selectedPack: "Pack sélectionné", visibilityPack: "Pack visibilité X", includedCredit: "crédit inclus", total: "Total", discount: "Remise incluse", continue: "Continuer", reassurance: "Sans engagement · Aucun mot de passe demandé",
    },
    step2: {
      titleBefore: "Quel", titleFocus: "profil", titleAfter: "souhaitez-vous promouvoir ?", intro: "Entrez votre @ X (Twitter). Aucun mot de passe, aucun accès demandé. Le compte doit être public.", searchMode: "Recherche X", urlMode: "Profil X", urlLabel: "Votre @ X (Twitter)", invalidUrl: "Format invalide. 4-15 caractères : lettres, chiffres et underscore uniquement.", trackLabel: "Pseudo X", artistLabel: "Nom affiché", notFound: "Compte introuvable sur X.", emailLabel: "Votre e-mail (pour le reçu)", emailPlaceholder: "vous@exemple.com", emailHint: "On vous envoie uniquement votre facture. Pas de spam, jamais.", back: "Retour", pay: "Aller au paiement", loading: "Vérification...", trackFallback: "Votre profil", artistFallback: "Nom affiché", totalStreams: "Abonnés", monthlyListeners: "Abonnements", popularity: "Popularité", newTotal: "Nouveau total",
      errors: { missingUrl: "Entrez votre @ X (Twitter).", invalidUrl: "Entrez un @ X valide et public.", missingSearch: "Entrez votre @ X (Twitter).", verifying: "Vérification du compte en cours...", notFound: "Ce compte est introuvable sur X.", missingTrack: "Entrez un @ X valide et public.", email: "Entrez votre e-mail pour recevoir le reçu." },
    },
    step3: { titleBefore: "Plus qu'une", titleFocus: "étape", titleAfter: ".", subtitle: "Paiement sécurisé · préparation de la campagne après confirmation.", summary: "Récapitulatif", recipient: "Profil destinataire", edit: "Modifier", trackFallback: "Votre profil", visibilityPack: "Pack visibilité X", includedCredit: "crédit inclus", campaignCredit: "Crédit de campagne", free: "OFFERT", coupon: "Code promo", couponPlaceholder: "CODE PROMO", applied: "✓ Appliqué", apply: "Appliquer", saving: "✓ -5% appliqué · économie", total: "Total TTC", securePayment: "Paiement sécurisé", legalBefore: "En finalisant le paiement vous acceptez nos", legalAfter: "Aucun abonnement caché.", terms: "CGV", gdpr: "RGPD", backToPacks: "Retour au choix des packs" },
    why: { eyebrow: "Pourquoi Fanovera", title1: "Des abonnés X", title2: "progressifs", title3: "et soignés.", items: [["Audience ciblée", "Notre IA aide à présenter votre profil à une audience cohérente avec votre thématique."], ["Compte préservé", "Aucun accès au compte, aucune publication à votre place, aucune action directe sur votre profil."], ["Sans mot de passe", "Juste votre @ public pour préparer la campagne de visibilité."], ["Suivi inclus", "Si le volume prévu n'est pas atteint, notre support vérifie et prolonge la campagne."]] },
    reviews: { eyebrow: "Avis clients", rating: "2 348 avis", dates: ["il y a 2 jours", "il y a 7 jours", "il y a 5 jours", "il y a 10 jours", "il y a 5 jours", "il y a 12 jours", "il y a 14 jours", "il y a 15 jours"], texts: ["Progression régulière et campagne bien suivie. Je recommande.", "Mise en route rapide, suivi clair et rythme progressif.", "Les abonnés ont augmenté progressivement sur 10 jours.", "Première campagne X, service sérieux et suivi clair.", "Bonne progression de mon profil en plusieurs semaines.", "Rien à redire, la progression correspond à ce qui était annoncé.", "Service client réactif et suivi au rendez-vous.", "Ma communauté a progressé de façon régulière."] },
    faq: { titleBefore: "Vos questions,", titleFocus: "nos réponses", items: [["Comment fonctionne la mise en avant ?", "Nous préparons une campagne de visibilité autour de votre profil X et de votre thématique. L'objectif est de présenter votre contenu à une audience plus pertinente, avec un rythme progressif et mesuré."], ["Est-ce que je dois vous donner mon mot de passe ?", "Jamais. Nous avons uniquement besoin de votre @ X public. Aucun accès au compte n'est demandé."], ["Est-ce que vous agissez sur mon compte ?", "Non. Nous ne nous connectons pas à votre compte et nous ne publions rien à votre place. Le service s'appuie sur une mise en avant externe et progressive."], ["Quand la campagne démarre-t-elle ?", "La préparation démarre après confirmation du paiement. Le déploiement est progressif et peut s'étaler sur plusieurs jours selon le volume choisi."], ["Que se passe-t-il si le volume n'est pas atteint ?", "Notre support vérifie la campagne et peut prolonger la mise en avant sans frais supplémentaires lorsque le volume prévu n'est pas atteint."], ["Les statistiques apparaissent-elles tout de suite ?", "Les statistiques peuvent varier selon les contrôles et délais propres à X. Le déploiement reste progressif et suivi."]] },
    footer: { desc: "Stratégie de présence en ligne assistée par IA. Campagnes ciblées, suivi clair et progression mesurée.", networks: "Réseaux", help: "Aide", how: "Comment ça marche", support: "Support campagne", tracking: "Suivi de commande", legal: "Légal", legalNotice: "Mentions légales", privacy: "Confidentialité", cookies: "Cookies", madeIn: "Made in Paris" },
  },
  en: {
    header: { allNetworks: "All networks", tracking: "Tracking", ratingText: "2,348 reviews", home: "Home" },
    stepper: ["Choose a pack", "Your profile", "Secure payment"],
    step1: { titleBefore: "Targeted X visibility", titleFocus: "focused", titleAfter: "and progressive.", volume: "Which volume?", audience: "Followers", included: "included", campaign: "Your campaign", selectedPack: "Selected pack", visibilityPack: "X visibility pack", includedCredit: "included credit", total: "Total", discount: "Discount included", continue: "Continue", reassurance: "No commitment · No password required" },
    step2: { titleBefore: "Which", titleFocus: "profile", titleAfter: "would you like to promote?", intro: "Enter your @ X (Twitter). No password and no account access requested. The account must be public.", searchMode: "X search", urlMode: "X profile", urlLabel: "Your @ X (Twitter)", invalidUrl: "Invalid format. 4-15 characters: letters, numbers and underscore only.", trackLabel: "X handle", artistLabel: "Display name", notFound: "Account not found on X.", emailLabel: "Your email (for the receipt)", emailPlaceholder: "you@example.com", emailHint: "We only send your invoice. No spam, ever.", back: "Back", pay: "Go to payment", loading: "Checking...", trackFallback: "Your profile", artistFallback: "Display name", totalStreams: "Followers", monthlyListeners: "Following", popularity: "Popularity", newTotal: "New total", errors: { missingUrl: "Enter your @ X (Twitter).", invalidUrl: "Enter a valid and public @ X.", missingSearch: "Enter your @ X (Twitter).", verifying: "Account verification in progress...", notFound: "This account cannot be found on X.", missingTrack: "Enter a valid and public @ X.", email: "Enter your email to receive the receipt." } },
    step3: { titleBefore: "One", titleFocus: "step", titleAfter: "left.", subtitle: "Secure payment · campaign preparation after confirmation.", summary: "Summary", recipient: "Recipient profile", edit: "Edit", trackFallback: "Your profile", visibilityPack: "X visibility pack", includedCredit: "included credit", campaignCredit: "Campaign credit", free: "FREE", coupon: "Promo code", couponPlaceholder: "PROMO CODE", applied: "✓ Applied", apply: "Apply", saving: "✓ -5% applied · saving", total: "Total incl. tax", securePayment: "Secure payment", legalBefore: "By completing payment, you accept our", legalAfter: "No hidden subscription.", terms: "Terms", gdpr: "GDPR", backToPacks: "Back to pack selection" },
    why: { eyebrow: "Why Fanovera", title1: "Progressive", title2: "X followers", title3: "with careful delivery.", items: [["Focused audience", "Our AI helps present your profile to an audience aligned with your topic."], ["Account protected", "No account access, no posting on your behalf, and no direct action on your profile."], ["No password", "Only your public @ is needed to prepare the visibility campaign."], ["Follow-up included", "If the planned volume is not reached, our support team reviews and extends the campaign."]] },
    reviews: { eyebrow: "Customer reviews", rating: "2,348 reviews", dates: ["2 days ago", "7 days ago", "5 days ago", "10 days ago", "5 days ago", "12 days ago", "14 days ago", "15 days ago"], texts: ["Steady progress and a well-monitored campaign. I recommend it.", "Fast setup, clear tracking and a progressive pace.", "Followers increased gradually over 10 days.", "First X campaign, serious service and clear follow-up.", "Good progress on my profile over several weeks.", "Nothing to add, the progress matched what was announced.", "Responsive support and reliable follow-up.", "My community grew at a steady pace."] },
    faq: { titleBefore: "Your questions,", titleFocus: "our answers", items: [["How does the visibility campaign work?", "We prepare a visibility campaign around your X profile and topic. The goal is to present your content to a more relevant audience, with a measured and progressive pace."], ["Do I need to give you my password?", "Never. We only need your public @ X. No account access is requested."], ["Do you act on my account?", "No. We do not log into your account and we do not publish anything on your behalf. The service relies on external and progressive promotion."], ["When does the campaign start?", "Preparation starts after payment confirmation. Deployment is progressive and can span several days depending on the selected volume."], ["What happens if the volume is not reached?", "Our support team reviews the campaign and can extend the promotion at no extra cost when the planned volume is not reached."], ["Do stats appear immediately?", "Stats can vary depending on X's own checks and delays. Deployment remains progressive and monitored."]] },
    footer: { desc: "AI-assisted online presence strategy. Focused campaigns, clear tracking and measured progress.", networks: "Networks", help: "Help", how: "How it works", support: "Campaign support", tracking: "Order tracking", legal: "Legal", legalNotice: "Legal notice", privacy: "Privacy", cookies: "Cookies", madeIn: "Made in Paris" },
  },
} as const;

type Widen<T> = T extends string ? string : T extends readonly (infer U)[] ? readonly Widen<U>[] : T extends object ? { readonly [K in keyof T]: Widen<T[K]> } : T;
type XCopy = Widen<(typeof copy)["en"]>;

const localized: Record<SupportedLocale, XCopy> = {
  fr: copy.fr,
  en: copy.en,
  es: translateLocalCopy(copy.fr, "es"),
  pt: translateLocalCopy(copy.fr, "pt"),
  de: translateLocalCopy(copy.fr, "de"),
  it: translateLocalCopy(copy.fr, "it"),
  tr: translateLocalCopy(copy.fr, "tr"),
};

export function useXCopy() {
  const { locale } = useI18n();
  const manualLocale =
    typeof window !== "undefined" && window.localStorage.getItem("fanovera_locale_mode") === "manual"
      ? (window.localStorage.getItem("fanovera_locale") as SupportedLocale | null)
      : null;
  return localized[manualLocale || locale] || copy.fr;
}
