import { useI18n } from "../i18n/I18nProvider";
import type { SupportedLocale } from "../i18n/types";
import { applyPerformanceProductCopy, applyBlackhatProductCopy } from "../lib/performanceCopy";
import { useMarketingMode } from "../marketing/MarketingModeProvider";

const copy = {
  fr: {
    header: { allNetworks: "Tous les réseaux", tracking: "Suivi", ratingText: "2 348 avis", home: "Accueil" },
    stepper: ["Choisir un pack", "Votre profil", "Paiement sécurisé"],
    step1: {
      titleBefore: "Une visibilité X", titleFocus: "ciblée", titleAfter: "& progressive.", volume: "Quel volume ?", audience: "Abonnés", included: "inclus", campaign: "Votre campagne", selectedPack: "Pack sélectionné", visibilityPack: "Pack visibilité X", includedCredit: "crédit inclus", total: "Total", discount: "Remise incluse", continue: "Continuer", reassurance: "Sans engagement · Aucun mot de passe · Démarrage sous 1–6 h",
    },
    step2: {
      titleBefore: "Quel", titleFocus: "profil", titleAfter: "souhaitez-vous promouvoir ?", intro: "Entrez votre @ X (Twitter). Aucun mot de passe, aucun accès demandé. Le compte doit être public.", searchMode: "Recherche X", urlMode: "Profil X", urlLabel: "Votre @ X (Twitter)", invalidUrl: "Format invalide. 4-15 caractères : lettres, chiffres et underscore uniquement.", trackLabel: "Pseudo X", artistLabel: "Nom affiché", notFound: "Compte introuvable sur X.", emailLabel: "Votre e-mail (pour le reçu)", emailPlaceholder: "vous@exemple.com", emailHint: "On vous envoie uniquement votre facture. Pas de spam, jamais.", back: "Retour", pay: "Aller au paiement", loading: "Vérification...", trackFallback: "Votre profil", artistFallback: "Nom affiché", totalStreams: "Abonnés", monthlyListeners: "Abonnements", popularity: "Popularité", newTotal: "Nouveau total",
      errors: { missingUrl: "Entrez votre @ X (Twitter).", invalidUrl: "Entrez un @ X valide et public.", missingSearch: "Entrez votre @ X (Twitter).", verifying: "Vérification du compte en cours...", notFound: "Ce compte est introuvable sur X.", missingTrack: "Entrez un @ X valide et public.", email: "Entrez votre e-mail pour recevoir le reçu." },
    },
    step3: { titleBefore: "Plus qu'une", titleFocus: "étape", titleAfter: ".", subtitle: "Paiement sécurisé · préparation de la campagne après confirmation.", summary: "Récapitulatif", recipient: "Profil destinataire", edit: "Modifier", trackFallback: "Votre profil", visibilityPack: "Pack visibilité X", includedCredit: "crédit inclus", included: "inclus", campaignCredit: "Crédit de campagne", free: "OFFERT", coupon: "Code promo", couponPlaceholder: "CODE PROMO", applied: "✓ Appliqué", apply: "Appliquer", saving: "✓ -5% appliqué · économie", total: "Total TTC", securePayment: "Paiement sécurisé", legalBefore: "En finalisant le paiement vous acceptez nos", legalAfter: "Aucun abonnement caché.", terms: "CGV", gdpr: "RGPD", backToPacks: "Retour au choix des packs" },
    why: { eyebrow: "Pourquoi Fanovera", title1: "Des abonnés X", title2: "progressifs", title3: "et soignés.", items: [["Audience ciblée", "Notre IA aide à présenter votre profil à une audience cohérente avec votre thématique."], ["Compte préservé", "Aucun accès au compte, aucune publication à votre place, aucune action directe sur votre profil."], ["Sans mot de passe", "Juste votre @ public pour préparer la campagne de visibilité."], ["Suivi inclus", "Si le volume prévu n'est pas atteint, notre support vérifie et prolonge la campagne."]] },
    reviews: { eyebrow: "Avis clients", rating: "2 348 avis", dates: ["il y a 2 jours", "il y a 7 jours", "il y a 5 jours", "il y a 10 jours", "il y a 5 jours", "il y a 12 jours", "il y a 14 jours", "il y a 15 jours"], texts: ["Progression régulière et campagne bien suivie. Je recommande.", "Mise en route rapide, suivi clair et rythme progressif.", "Les abonnés ont augmenté progressivement sur 10 jours.", "Première campagne X, service sérieux et suivi clair.", "Bonne progression de mon profil en plusieurs semaines.", "Rien à redire, la progression correspond à ce qui était annoncé.", "Service client réactif et suivi au rendez-vous.", "Ma communauté a progressé de façon régulière."] },
    faq: { titleBefore: "Vos questions,", titleFocus: "nos réponses", items: [["Comment fonctionne la mise en avant ?", "Nous préparons une campagne de visibilité autour de votre profil X et de votre thématique. L'objectif est de présenter votre contenu à une audience plus pertinente, avec un rythme progressif et mesuré."], ["Est-ce que je dois vous donner mon mot de passe ?", "Jamais. Nous avons uniquement besoin de votre @ X public. Aucun accès au compte n'est demandé."], ["Est-ce que vous agissez sur mon compte ?", "Non. Nous ne nous connectons pas à votre compte et nous ne publions rien à votre place. Le service s'appuie sur une mise en avant externe et progressive."], ["Quand la campagne démarre-t-elle ?", "La préparation démarre après confirmation du paiement. Le déploiement est progressif et peut s'étaler sur plusieurs jours selon le volume choisi."], ["Que se passe-t-il si le volume n'est pas atteint ?", "Notre support vérifie la campagne et peut prolonger la mise en avant sans frais supplémentaires lorsque le volume prévu n'est pas atteint."], ["Les statistiques apparaissent-elles tout de suite ?", "Les statistiques peuvent varier selon les contrôles et délais propres à X. Le déploiement reste progressif et suivi."]] },
    footer: { desc: "Stratégie de présence en ligne assistée par IA. Campagnes ciblées, suivi clair et progression mesurée.", networks: "Réseaux", help: "Aide", how: "Comment ça marche", support: "Support campagne", tracking: "Suivi de commande", legal: "Légal", legalNotice: "Mentions légales", privacy: "Confidentialité", cookies: "Cookies", madeIn: "Made in Paris" },
  },
  en: {
    header: { allNetworks: "All networks", tracking: "Tracking", ratingText: "2,348 reviews", home: "Home" },
    stepper: ["Choose a pack", "Your profile", "Secure payment"],
    step1: { titleBefore: "Targeted X visibility", titleFocus: "focused", titleAfter: "and progressive.", volume: "Which volume?", audience: "Followers", included: "included", campaign: "Your campaign", selectedPack: "Selected pack", visibilityPack: "X visibility pack", includedCredit: "included credit", total: "Total", discount: "Discount included", continue: "Continue", reassurance: "No commitment · No password · Starts in 1–6 h" },
    step2: { titleBefore: "Which", titleFocus: "profile", titleAfter: "would you like to promote?", intro: "Enter your @ X (Twitter). No password and no account access requested. The account must be public.", searchMode: "X search", urlMode: "X profile", urlLabel: "Your @ X (Twitter)", invalidUrl: "Invalid format. 4-15 characters: letters, numbers and underscore only.", trackLabel: "X handle", artistLabel: "Display name", notFound: "Account not found on X.", emailLabel: "Your email (for the receipt)", emailPlaceholder: "you@example.com", emailHint: "We only send your invoice. No spam, ever.", back: "Back", pay: "Go to payment", loading: "Checking...", trackFallback: "Your profile", artistFallback: "Display name", totalStreams: "Followers", monthlyListeners: "Following", popularity: "Popularity", newTotal: "New total", errors: { missingUrl: "Enter your @ X (Twitter).", invalidUrl: "Enter a valid and public @ X.", missingSearch: "Enter your @ X (Twitter).", verifying: "Account verification in progress...", notFound: "This account cannot be found on X.", missingTrack: "Enter a valid and public @ X.", email: "Enter your email to receive the receipt." } },
    step3: { titleBefore: "One", titleFocus: "step", titleAfter: "left.", subtitle: "Secure payment · campaign preparation after confirmation.", summary: "Summary", recipient: "Recipient profile", edit: "Edit", trackFallback: "Your profile", visibilityPack: "X visibility pack", includedCredit: "included credit", included: "included", campaignCredit: "Campaign credit", free: "FREE", coupon: "Promo code", couponPlaceholder: "PROMO CODE", applied: "✓ Applied", apply: "Apply", saving: "✓ -5% applied · saving", total: "Total incl. tax", securePayment: "Secure payment", legalBefore: "By completing payment, you accept our", legalAfter: "No hidden subscription.", terms: "Terms", gdpr: "GDPR", backToPacks: "Back to pack selection" },
    why: { eyebrow: "Why Fanovera", title1: "Progressive", title2: "X followers", title3: "with careful delivery.", items: [["Focused audience", "Our AI helps present your profile to an audience aligned with your topic."], ["Account protected", "No account access, no posting on your behalf, and no direct action on your profile."], ["No password", "Only your public @ is needed to prepare the visibility campaign."], ["Follow-up included", "If the planned volume is not reached, our support team reviews and extends the campaign."]] },
    reviews: { eyebrow: "Customer reviews", rating: "2,348 reviews", dates: ["2 days ago", "7 days ago", "5 days ago", "10 days ago", "5 days ago", "12 days ago", "14 days ago", "15 days ago"], texts: ["Steady progress and a well-monitored campaign. I recommend it.", "Fast setup, clear tracking and a progressive pace.", "Followers increased gradually over 10 days.", "First X campaign, serious service and clear follow-up.", "Good progress on my profile over several weeks.", "Nothing to add, the progress matched what was announced.", "Responsive support and reliable follow-up.", "My community grew at a steady pace."] },
    faq: { titleBefore: "Your questions,", titleFocus: "our answers", items: [["How does the visibility campaign work?", "We prepare a visibility campaign around your X profile and topic. The goal is to present your content to a more relevant audience, with a measured and progressive pace."], ["Do I need to give you my password?", "Never. We only need your public @ X. No account access is requested."], ["Do you act on my account?", "No. We do not log into your account and we do not publish anything on your behalf. The service relies on external and progressive promotion."], ["When does the campaign start?", "Preparation starts after payment confirmation. Deployment is progressive and can span several days depending on the selected volume."], ["What happens if the volume is not reached?", "Our support team reviews the campaign and can extend the promotion at no extra cost when the planned volume is not reached."], ["Do stats appear immediately?", "Stats can vary depending on X's own checks and delays. Deployment remains progressive and monitored."]] },
    footer: { desc: "AI-assisted online presence strategy. Focused campaigns, clear tracking and measured progress.", networks: "Networks", help: "Help", how: "How it works", support: "Campaign support", tracking: "Order tracking", legal: "Legal", legalNotice: "Legal notice", privacy: "Privacy", cookies: "Cookies", madeIn: "Made in Paris" },
  },
  es: {
    header: { allNetworks: "Todas las redes", tracking: "Seguimiento", ratingText: "2.348 reseñas", home: "Inicio" },
    stepper: ["Elegir un pack", "Tu perfil", "Pago seguro"],
    step1: { titleBefore: "Visibilidad en X", titleFocus: "dirigida", titleAfter: "y progresiva.", volume: "¿Qué volumen?", audience: "Seguidores", included: "incluido", campaign: "Tu campaña", selectedPack: "Pack seleccionado", visibilityPack: "Pack de visibilidad X", includedCredit: "crédito incluido", total: "Total", discount: "Descuento incluido", continue: "Continuar", reassurance: "Sin compromiso · Sin contraseña · Inicio en 1–6 h" },
    step2: { titleBefore: "¿Qué", titleFocus: "perfil", titleAfter: "quieres promocionar?", intro: "Introduce tu @ X (Twitter). Sin contraseña, sin acceso a la cuenta. La cuenta debe ser pública.", searchMode: "Búsqueda X", urlMode: "Perfil X", urlLabel: "Tu @ X (Twitter)", invalidUrl: "Formato inválido. 4-15 caracteres: letras, números y guion bajo.", trackLabel: "Usuario X", artistLabel: "Nombre mostrado", notFound: "Cuenta no encontrada en X.", emailLabel: "Tu email (para el recibo)", emailPlaceholder: "tu@ejemplo.com", emailHint: "Solo enviamos tu factura. Nunca spam.", back: "Atrás", pay: "Ir al pago", loading: "Verificando...", trackFallback: "Tu perfil", artistFallback: "Nombre mostrado", totalStreams: "Seguidores", monthlyListeners: "Siguiendo", popularity: "Popularidad", newTotal: "Nuevo total", errors: { missingUrl: "Introduce tu @ X (Twitter).", invalidUrl: "Introduce un @ X válido y público.", missingSearch: "Introduce tu @ X (Twitter).", verifying: "Verificación de la cuenta en curso...", notFound: "Esta cuenta no se encuentra en X.", missingTrack: "Introduce un @ X válido y público.", email: "Introduce tu email para recibir el recibo." } },
    step3: { titleBefore: "Solo un", titleFocus: "paso", titleAfter: "más.", subtitle: "Pago seguro · preparación de la campaña tras la confirmación.", summary: "Resumen", recipient: "Perfil destinatario", edit: "Editar", trackFallback: "Tu perfil", visibilityPack: "Pack de visibilidad X", includedCredit: "crédito incluido", included: "incluido", campaignCredit: "Crédito de campaña", free: "GRATIS", coupon: "Código promo", couponPlaceholder: "CÓDIGO PROMO", applied: "✓ Aplicado", apply: "Aplicar", saving: "✓ -5% aplicado · ahorro", total: "Total IVA incl.", securePayment: "Pago seguro", legalBefore: "Al finalizar el pago aceptas nuestros", legalAfter: "Sin suscripción oculta.", terms: "Términos", gdpr: "RGPD", backToPacks: "Volver a la selección de packs" },
    why: { eyebrow: "Por qué Fanovera", title1: "Seguidores X", title2: "progresivos", title3: "y cuidados.", items: [["Audiencia dirigida", "Nuestra IA ayuda a presentar tu perfil a una audiencia coherente con tu temática."], ["Cuenta protegida", "Sin acceso a la cuenta, sin publicaciones en tu nombre, sin acciones directas en tu perfil."], ["Sin contraseña", "Solo tu @ público para preparar la campaña de visibilidad."], ["Seguimiento incluido", "Si no se alcanza el volumen previsto, nuestro soporte revisa y prolonga la campaña."]] },
    reviews: { eyebrow: "Reseñas de clientes", rating: "2.348 reseñas", dates: ["hace 2 días", "hace 7 días", "hace 5 días", "hace 10 días", "hace 5 días", "hace 12 días", "hace 14 días", "hace 15 días"], texts: ["Progresión regular y campaña bien seguida. Lo recomiendo.", "Inicio rápido, seguimiento claro y ritmo progresivo.", "Los seguidores aumentaron progresivamente en 10 días.", "Primera campaña X, servicio serio y seguimiento claro.", "Buen progreso de mi perfil durante varias semanas.", "Nada que añadir, el progreso corresponde a lo anunciado.", "Servicio al cliente reactivo y seguimiento al día.", "Mi comunidad ha progresado de forma regular."] },
    faq: { titleBefore: "Tus preguntas,", titleFocus: "nuestras respuestas", items: [["¿Cómo funciona la promoción?", "Preparamos una campaña de visibilidad alrededor de tu perfil X y de tu temática. El objetivo es presentar tu contenido a una audiencia más relevante, con un ritmo progresivo y medido."], ["¿Debo darte mi contraseña?", "Nunca. Solo necesitamos tu @ X público. No se solicita acceso a la cuenta."], ["¿Actúas sobre mi cuenta?", "No. No iniciamos sesión en tu cuenta ni publicamos nada en tu nombre. El servicio se basa en una promoción externa y progresiva."], ["¿Cuándo empieza la campaña?", "La preparación empieza tras la confirmación del pago. El despliegue es progresivo y puede durar varios días según el volumen elegido."], ["¿Qué pasa si no se alcanza el volumen?", "Nuestro soporte revisa la campaña y puede prolongar la promoción sin coste adicional cuando no se alcanza el volumen previsto."], ["¿Las estadísticas aparecen de inmediato?", "Las estadísticas pueden variar según los controles y plazos propios de X. El despliegue sigue siendo progresivo y supervisado."]] },
    footer: { desc: "Estrategia de presencia online asistida por IA. Campañas dirigidas, seguimiento claro y progreso medido.", networks: "Redes", help: "Ayuda", how: "Cómo funciona", support: "Soporte de campaña", tracking: "Seguimiento del pedido", legal: "Legal", legalNotice: "Aviso legal", privacy: "Privacidad", cookies: "Cookies", madeIn: "Made in Paris" },
  },
  pt: {
    header: { allNetworks: "Todas as redes", tracking: "Acompanhamento", ratingText: "2.348 avaliações", home: "Início" },
    stepper: ["Escolher um pack", "Seu perfil", "Pagamento seguro"],
    step1: { titleBefore: "Visibilidade no X", titleFocus: "direcionada", titleAfter: "e progressiva.", volume: "Qual volume?", audience: "Seguidores", included: "incluído", campaign: "Sua campanha", selectedPack: "Pack selecionado", visibilityPack: "Pack de visibilidade X", includedCredit: "crédito incluído", total: "Total", discount: "Desconto incluído", continue: "Continuar", reassurance: "Sem compromisso · Sem senha · Início em 1–6 h" },
    step2: { titleBefore: "Qual", titleFocus: "perfil", titleAfter: "deseja promover?", intro: "Digite seu @ X (Twitter). Sem senha, sem acesso à conta. A conta deve ser pública.", searchMode: "Busca X", urlMode: "Perfil X", urlLabel: "Seu @ X (Twitter)", invalidUrl: "Formato inválido. 4-15 caracteres: letras, números e underscore.", trackLabel: "Usuário X", artistLabel: "Nome exibido", notFound: "Conta não encontrada no X.", emailLabel: "Seu email (para o recibo)", emailPlaceholder: "voce@exemplo.com", emailHint: "Enviamos apenas sua nota. Nunca spam.", back: "Voltar", pay: "Ir ao pagamento", loading: "Verificando...", trackFallback: "Seu perfil", artistFallback: "Nome exibido", totalStreams: "Seguidores", monthlyListeners: "Seguindo", popularity: "Popularidade", newTotal: "Novo total", errors: { missingUrl: "Digite seu @ X (Twitter).", invalidUrl: "Digite um @ X válido e público.", missingSearch: "Digite seu @ X (Twitter).", verifying: "Verificação da conta em andamento...", notFound: "Não encontramos esta conta no X.", missingTrack: "Digite um @ X válido e público.", email: "Digite seu email para receber o recibo." } },
    step3: { titleBefore: "Falta apenas", titleFocus: "um passo", titleAfter: ".", subtitle: "Pagamento seguro · preparação da campanha após confirmação.", summary: "Resumo", recipient: "Perfil destinatário", edit: "Editar", trackFallback: "Seu perfil", visibilityPack: "Pack de visibilidade X", includedCredit: "crédito incluído", included: "incluído", campaignCredit: "Crédito de campanha", free: "GRÁTIS", coupon: "Código promocional", couponPlaceholder: "CÓDIGO PROMO", applied: "✓ Aplicado", apply: "Aplicar", saving: "✓ -5% aplicado · economia", total: "Total com impostos", securePayment: "Pagamento seguro", legalBefore: "Ao finalizar o pagamento você aceita nossos", legalAfter: "Sem assinatura oculta.", terms: "Termos", gdpr: "LGPD", backToPacks: "Voltar à escolha dos packs" },
    why: { eyebrow: "Por que Fanovera", title1: "Seguidores X", title2: "progressivos", title3: "e cuidadosos.", items: [["Audiência direcionada", "Nossa IA ajuda a apresentar seu perfil a uma audiência coerente com sua temática."], ["Conta preservada", "Sem acesso à conta, sem publicações em seu nome, sem ações diretas no seu perfil."], ["Sem senha", "Apenas seu @ público para preparar a campanha de visibilidade."], ["Acompanhamento incluído", "Se o volume previsto não for atingido, nosso suporte revisa e estende a campanha."]] },
    reviews: { eyebrow: "Avaliações de clientes", rating: "2.348 avaliações", dates: ["há 2 dias", "há 7 dias", "há 5 dias", "há 10 dias", "há 5 dias", "há 12 dias", "há 14 dias", "há 15 dias"], texts: ["Progresso regular e campanha bem acompanhada. Recomendo.", "Início rápido, acompanhamento claro e ritmo progressivo.", "Os seguidores aumentaram progressivamente em 10 dias.", "Primeira campanha X, serviço sério e acompanhamento claro.", "Bom progresso do meu perfil durante várias semanas.", "Nada a dizer, o progresso corresponde ao anunciado.", "Suporte responsivo e acompanhamento pontual.", "Minha comunidade progrediu de forma regular."] },
    faq: { titleBefore: "Suas perguntas,", titleFocus: "nossas respostas", items: [["Como funciona a promoção?", "Preparamos uma campanha de visibilidade em torno do seu perfil X e da sua temática. O objetivo é apresentar seu conteúdo a uma audiência mais relevante, com um ritmo progressivo e medido."], ["Preciso fornecer minha senha?", "Nunca. Precisamos apenas do seu @ X público. Nenhum acesso à conta é solicitado."], ["Vocês agem na minha conta?", "Não. Não acessamos sua conta e não publicamos nada em seu nome. O serviço se baseia em uma promoção externa e progressiva."], ["Quando a campanha começa?", "A preparação começa após a confirmação do pagamento. A implantação é progressiva e pode durar vários dias conforme o volume escolhido."], ["O que acontece se o volume não for atingido?", "Nosso suporte revisa a campanha e pode estender a promoção sem custos adicionais quando o volume previsto não é atingido."], ["As estatísticas aparecem imediatamente?", "As estatísticas podem variar conforme os controles e prazos próprios do X. A implantação continua progressiva e monitorada."]] },
    footer: { desc: "Estratégia de presença online com IA. Campanhas direcionadas, acompanhamento claro e progresso medido.", networks: "Redes", help: "Ajuda", how: "Como funciona", support: "Suporte de campanha", tracking: "Acompanhamento do pedido", legal: "Legal", legalNotice: "Aviso legal", privacy: "Privacidade", cookies: "Cookies", madeIn: "Made in Paris" },
  },
  de: {
    header: { allNetworks: "Alle Netzwerke", tracking: "Tracking", ratingText: "2.348 Bewertungen", home: "Startseite" },
    stepper: ["Paket wählen", "Dein Profil", "Sichere Zahlung"],
    step1: { titleBefore: "Gezielte X-Sichtbarkeit", titleFocus: "fokussiert", titleAfter: "und progressiv.", volume: "Welches Volumen?", audience: "Follower", included: "inklusive", campaign: "Deine Kampagne", selectedPack: "Ausgewähltes Paket", visibilityPack: "X-Sichtbarkeitspaket", includedCredit: "Guthaben inklusive", total: "Gesamt", discount: "Rabatt enthalten", continue: "Weiter", reassurance: "Keine Verpflichtung · Kein Passwort · Start in 1–6 h" },
    step2: { titleBefore: "Welches", titleFocus: "Profil", titleAfter: "möchtest du bewerben?", intro: "Gib dein @ X (Twitter) ein. Kein Passwort, kein Kontozugriff. Das Konto muss öffentlich sein.", searchMode: "X-Suche", urlMode: "X-Profil", urlLabel: "Dein @ X (Twitter)", invalidUrl: "Ungültiges Format. 4-15 Zeichen: Buchstaben, Zahlen und Unterstrich.", trackLabel: "X-Handle", artistLabel: "Anzeigename", notFound: "Konto auf X nicht gefunden.", emailLabel: "Deine E-Mail (für die Quittung)", emailPlaceholder: "du@beispiel.com", emailHint: "Wir senden nur deine Rechnung. Niemals Spam.", back: "Zurück", pay: "Zur Zahlung", loading: "Wird geprüft...", trackFallback: "Dein Profil", artistFallback: "Anzeigename", totalStreams: "Follower", monthlyListeners: "Folgt", popularity: "Beliebtheit", newTotal: "Neue Summe", errors: { missingUrl: "Gib dein @ X (Twitter) ein.", invalidUrl: "Gib ein gültiges und öffentliches @ X ein.", missingSearch: "Gib dein @ X (Twitter) ein.", verifying: "Kontoprüfung läuft...", notFound: "Dieses Konto kann auf X nicht gefunden werden.", missingTrack: "Gib ein gültiges und öffentliches @ X ein.", email: "Gib deine E-Mail ein, um die Quittung zu erhalten." } },
    step3: { titleBefore: "Nur noch ein", titleFocus: "Schritt", titleAfter: ".", subtitle: "Sichere Zahlung · Kampagnenvorbereitung nach Bestätigung.", summary: "Zusammenfassung", recipient: "Empfänger-Profil", edit: "Bearbeiten", trackFallback: "Dein Profil", visibilityPack: "X-Sichtbarkeitspaket", includedCredit: "Guthaben inklusive", included: "inklusive", campaignCredit: "Kampagnen-Guthaben", free: "GRATIS", coupon: "Promo-Code", couponPlaceholder: "PROMO-CODE", applied: "✓ Angewendet", apply: "Anwenden", saving: "✓ -5% angewendet · Ersparnis", total: "Gesamt inkl. MwSt.", securePayment: "Sichere Zahlung", legalBefore: "Mit Abschluss der Zahlung akzeptierst du unsere", legalAfter: "Kein verstecktes Abonnement.", terms: "AGB", gdpr: "DSGVO", backToPacks: "Zurück zur Paketauswahl" },
    why: { eyebrow: "Warum Fanovera", title1: "X-Follower", title2: "progressiv", title3: "und sorgfältig geliefert.", items: [["Fokussierte Zielgruppe", "Unsere KI hilft, dein Profil einer Zielgruppe zu präsentieren, die zu deinem Thema passt."], ["Konto geschützt", "Kein Kontozugriff, keine Beiträge in deinem Namen, keine direkten Aktionen auf deinem Profil."], ["Kein Passwort", "Nur dein öffentliches @ wird benötigt, um die Sichtbarkeitskampagne vorzubereiten."], ["Nachverfolgung inklusive", "Wenn das geplante Volumen nicht erreicht wird, prüft und verlängert unser Support die Kampagne."]] },
    reviews: { eyebrow: "Kundenbewertungen", rating: "2.348 Bewertungen", dates: ["vor 2 Tagen", "vor 7 Tagen", "vor 5 Tagen", "vor 10 Tagen", "vor 5 Tagen", "vor 12 Tagen", "vor 14 Tagen", "vor 15 Tagen"], texts: ["Stetiger Fortschritt und gut überwachte Kampagne. Ich empfehle es.", "Schneller Start, klare Nachverfolgung und progressives Tempo.", "Die Follower sind über 10 Tage schrittweise gestiegen.", "Erste X-Kampagne, seriöser Service und klare Nachverfolgung.", "Guter Fortschritt meines Profils über mehrere Wochen.", "Nichts hinzuzufügen, der Fortschritt entsprach dem Angekündigten.", "Reaktionsschneller Support und zuverlässige Nachverfolgung.", "Meine Community ist gleichmäßig gewachsen."] },
    faq: { titleBefore: "Deine Fragen,", titleFocus: "unsere Antworten", items: [["Wie funktioniert die Sichtbarkeitskampagne?", "Wir bereiten eine Sichtbarkeitskampagne rund um dein X-Profil und dein Thema vor. Ziel ist es, deine Inhalte einer relevanteren Zielgruppe zu präsentieren, mit gemessenem und progressivem Tempo."], ["Muss ich mein Passwort geben?", "Niemals. Wir brauchen nur dein öffentliches @ X. Es wird kein Kontozugriff verlangt."], ["Greift ihr auf mein Konto zu?", "Nein. Wir loggen uns nicht in dein Konto ein und veröffentlichen nichts in deinem Namen. Der Service basiert auf einer externen und progressiven Bewerbung."], ["Wann startet die Kampagne?", "Die Vorbereitung beginnt nach Zahlungsbestätigung. Die Bereitstellung ist progressiv und kann je nach gewähltem Volumen mehrere Tage dauern."], ["Was passiert, wenn das Volumen nicht erreicht wird?", "Unser Support prüft die Kampagne und kann die Bewerbung kostenlos verlängern, wenn das geplante Volumen nicht erreicht wird."], ["Erscheinen die Statistiken sofort?", "Statistiken können je nach Xs eigenen Prüfungen und Verzögerungen variieren. Die Bereitstellung bleibt progressiv und überwacht."]] },
    footer: { desc: "KI-gestützte Online-Präsenzstrategie. Fokussierte Kampagnen, klare Nachverfolgung und gemessener Fortschritt.", networks: "Netzwerke", help: "Hilfe", how: "So funktioniert es", support: "Kampagnensupport", tracking: "Bestellverfolgung", legal: "Rechtliches", legalNotice: "Impressum", privacy: "Datenschutz", cookies: "Cookies", madeIn: "Made in Paris" },
  },
  it: {
    header: { allNetworks: "Tutte le reti", tracking: "Monitoraggio", ratingText: "2.348 recensioni", home: "Home" },
    stepper: ["Scegli un pacchetto", "Il tuo profilo", "Pagamento sicuro"],
    step1: { titleBefore: "Visibilità X", titleFocus: "mirata", titleAfter: "e progressiva.", volume: "Quale volume?", audience: "Follower", included: "incluso", campaign: "La tua campagna", selectedPack: "Pacchetto selezionato", visibilityPack: "Pacchetto visibilità X", includedCredit: "credito incluso", total: "Totale", discount: "Sconto incluso", continue: "Continua", reassurance: "Senza impegno · Senza password · Avvio in 1–6 h" },
    step2: { titleBefore: "Quale", titleFocus: "profilo", titleAfter: "vuoi promuovere?", intro: "Inserisci il tuo @ X (Twitter). Nessuna password, nessun accesso all'account. L'account deve essere pubblico.", searchMode: "Ricerca X", urlMode: "Profilo X", urlLabel: "Il tuo @ X (Twitter)", invalidUrl: "Formato non valido. 4-15 caratteri: lettere, numeri e underscore.", trackLabel: "Handle X", artistLabel: "Nome visualizzato", notFound: "Account non trovato su X.", emailLabel: "La tua email (per la ricevuta)", emailPlaceholder: "tu@esempio.com", emailHint: "Inviamo solo la tua fattura. Mai spam.", back: "Indietro", pay: "Vai al pagamento", loading: "Verifica...", trackFallback: "Il tuo profilo", artistFallback: "Nome visualizzato", totalStreams: "Follower", monthlyListeners: "Seguiti", popularity: "Popolarità", newTotal: "Nuovo totale", errors: { missingUrl: "Inserisci il tuo @ X (Twitter).", invalidUrl: "Inserisci un @ X valido e pubblico.", missingSearch: "Inserisci il tuo @ X (Twitter).", verifying: "Verifica dell'account in corso...", notFound: "Non troviamo questo account su X.", missingTrack: "Inserisci un @ X valido e pubblico.", email: "Inserisci la tua email per ricevere la ricevuta." } },
    step3: { titleBefore: "Manca solo", titleFocus: "un passaggio", titleAfter: ".", subtitle: "Pagamento sicuro · preparazione della campagna dopo conferma.", summary: "Riepilogo", recipient: "Profilo destinatario", edit: "Modifica", trackFallback: "Il tuo profilo", visibilityPack: "Pacchetto visibilità X", includedCredit: "credito incluso", included: "incluso", campaignCredit: "Credito di campagna", free: "GRATIS", coupon: "Codice promo", couponPlaceholder: "CODICE PROMO", applied: "✓ Applicato", apply: "Applica", saving: "✓ -5% applicato · risparmio", total: "Totale IVA inclusa", securePayment: "Pagamento sicuro", legalBefore: "Completando il pagamento accetti i nostri", legalAfter: "Nessun abbonamento nascosto.", terms: "Termini", gdpr: "GDPR", backToPacks: "Torna alla scelta dei pacchetti" },
    why: { eyebrow: "Perché Fanovera", title1: "Follower X", title2: "progressivi", title3: "e curati.", items: [["Audience mirata", "La nostra IA aiuta a presentare il tuo profilo a un'audience coerente con la tua tematica."], ["Account protetto", "Nessun accesso all'account, nessuna pubblicazione al tuo posto, nessuna azione diretta sul tuo profilo."], ["Senza password", "Solo il tuo @ pubblico per preparare la campagna di visibilità."], ["Monitoraggio incluso", "Se il volume previsto non viene raggiunto, il nostro supporto verifica e prolunga la campagna."]] },
    reviews: { eyebrow: "Recensioni clienti", rating: "2.348 recensioni", dates: ["2 giorni fa", "7 giorni fa", "5 giorni fa", "10 giorni fa", "5 giorni fa", "12 giorni fa", "14 giorni fa", "15 giorni fa"], texts: ["Progresso costante e campagna ben seguita. La consiglio.", "Avvio rapido, monitoraggio chiaro e ritmo progressivo.", "I follower sono aumentati progressivamente in 10 giorni.", "Prima campagna X, servizio serio e monitoraggio chiaro.", "Buon progresso del mio profilo in diverse settimane.", "Niente da dire, il progresso corrisponde a quanto annunciato.", "Supporto reattivo e monitoraggio puntuale.", "La mia community è cresciuta in modo regolare."] },
    faq: { titleBefore: "Le tue domande,", titleFocus: "le nostre risposte", items: [["Come funziona la promozione?", "Prepariamo una campagna di visibilità intorno al tuo profilo X e alla tua tematica. L'obiettivo è presentare il tuo contenuto a un'audience più rilevante, con un ritmo progressivo e misurato."], ["Devo darti la mia password?", "Mai. Abbiamo solo bisogno del tuo @ X pubblico. Nessun accesso all'account viene richiesto."], ["Agite sul mio account?", "No. Non accediamo al tuo account e non pubblichiamo nulla al tuo posto. Il servizio si basa su una promozione esterna e progressiva."], ["Quando inizia la campagna?", "La preparazione inizia dopo la conferma del pagamento. La distribuzione è progressiva e può durare diversi giorni a seconda del volume scelto."], ["Cosa succede se il volume non viene raggiunto?", "Il nostro supporto verifica la campagna e può prolungare la promozione senza costi aggiuntivi quando il volume previsto non viene raggiunto."], ["Le statistiche appaiono subito?", "Le statistiche possono variare in base ai controlli e ritardi propri di X. La distribuzione resta progressiva e monitorata."]] },
    footer: { desc: "Strategia di presenza online assistita da IA. Campagne mirate, monitoraggio chiaro e progresso misurato.", networks: "Reti", help: "Aiuto", how: "Come funziona", support: "Supporto campagna", tracking: "Monitoraggio ordine", legal: "Legale", legalNotice: "Note legali", privacy: "Privacy", cookies: "Cookies", madeIn: "Made in Paris" },
  },
  tr: {
    header: { allNetworks: "Tüm ağlar", tracking: "Takip", ratingText: "2.348 yorum", home: "Anasayfa" },
    stepper: ["Paket seç", "Profiliniz", "Güvenli ödeme"],
    step1: { titleBefore: "Hedefli X görünürlüğü", titleFocus: "odaklı", titleAfter: "ve aşamalı.", volume: "Hangi hacim?", audience: "Takipçiler", included: "dahil", campaign: "Kampanyanız", selectedPack: "Seçili paket", visibilityPack: "X görünürlük paketi", includedCredit: "kredi dahil", total: "Toplam", discount: "İndirim dahil", continue: "Devam", reassurance: "Taahhütsüz · Şifresiz · 1–6 saatte başlar" },
    step2: { titleBefore: "Hangi", titleFocus: "profili", titleAfter: "tanıtmak istiyorsunuz?", intro: "@ X (Twitter) kullanıcı adınızı girin. Şifre yok, hesap erişimi yok. Hesap herkese açık olmalı.", searchMode: "X arama", urlMode: "X profili", urlLabel: "@ X (Twitter) kullanıcı adınız", invalidUrl: "Geçersiz format. 4-15 karakter: harf, rakam ve alt çizgi.", trackLabel: "X kullanıcı adı", artistLabel: "Görünen ad", notFound: "Hesap X'te bulunamadı.", emailLabel: "E-postanız (makbuz için)", emailPlaceholder: "siz@ornek.com", emailHint: "Sadece faturanızı gönderiyoruz. Asla spam yok.", back: "Geri", pay: "Ödemeye git", loading: "Kontrol ediliyor...", trackFallback: "Profiliniz", artistFallback: "Görünen ad", totalStreams: "Takipçiler", monthlyListeners: "Takip edilen", popularity: "Popülerlik", newTotal: "Yeni toplam", errors: { missingUrl: "@ X (Twitter) kullanıcı adınızı girin.", invalidUrl: "Geçerli ve herkese açık bir @ X girin.", missingSearch: "@ X (Twitter) kullanıcı adınızı girin.", verifying: "Hesap doğrulaması devam ediyor...", notFound: "Bu hesap X'te bulunamıyor.", missingTrack: "Geçerli ve herkese açık bir @ X girin.", email: "Makbuzu almak için e-postanızı girin." } },
    step3: { titleBefore: "Sadece bir", titleFocus: "adım", titleAfter: "kaldı.", subtitle: "Güvenli ödeme · onaydan sonra kampanya hazırlığı.", summary: "Özet", recipient: "Alıcı profil", edit: "Düzenle", trackFallback: "Profiliniz", visibilityPack: "X görünürlük paketi", includedCredit: "kredi dahil", included: "dahil", campaignCredit: "Kampanya kredisi", free: "ÜCRETSİZ", coupon: "Promosyon kodu", couponPlaceholder: "PROMO KODU", applied: "✓ Uygulandı", apply: "Uygula", saving: "✓ -5% uygulandı · tasarruf", total: "KDV dahil toplam", securePayment: "Güvenli ödeme", legalBefore: "Ödemeyi tamamlayarak kabul ediyorsunuz:", legalAfter: "Gizli abonelik yok.", terms: "Şartlar", gdpr: "KVKK", backToPacks: "Paket seçimine dön" },
    why: { eyebrow: "Neden Fanovera", title1: "X takipçileri", title2: "aşamalı", title3: "ve özenli teslimatla.", items: [["Odaklı kitle", "AI'mız profilinizi konunuza uygun bir kitleye sunmaya yardımcı olur."], ["Hesap korunur", "Hesap erişimi yok, sizin adınıza paylaşım yok, profilinizde doğrudan eylem yok."], ["Şifresiz", "Görünürlük kampanyasını hazırlamak için sadece herkese açık @ adresiniz gerekli."], ["Takip dahil", "Planlanan hacme ulaşılmazsa, destek ekibimiz kampanyayı inceler ve uzatır."]] },
    reviews: { eyebrow: "Müşteri yorumları", rating: "2.348 yorum", dates: ["2 gün önce", "7 gün önce", "5 gün önce", "10 gün önce", "5 gün önce", "12 gün önce", "14 gün önce", "15 gün önce"], texts: ["İstikrarlı ilerleme ve iyi takip edilen kampanya. Tavsiye ederim.", "Hızlı başlangıç, net takip ve aşamalı ritim.", "Takipçiler 10 günde kademeli olarak arttı.", "İlk X kampanyam, ciddi hizmet ve net takip.", "Profilimde birkaç hafta boyunca iyi ilerleme.", "Söylenecek bir şey yok, ilerleme duyurulduğu gibi.", "Duyarlı destek ve güvenilir takip.", "Topluluğum düzenli olarak büyüdü."] },
    faq: { titleBefore: "Sorularınız,", titleFocus: "cevaplarımız", items: [["Görünürlük kampanyası nasıl çalışır?", "X profiliniz ve konunuz etrafında bir görünürlük kampanyası hazırlıyoruz. Amaç, içeriğinizi daha alakalı bir kitleye sunmak, ölçülü ve aşamalı bir ritimle."], ["Şifremi vermem gerekiyor mu?", "Asla. Sadece herkese açık @ X adresinize ihtiyacımız var. Hesap erişimi talep edilmez."], ["Hesabımda işlem yapıyor musunuz?", "Hayır. Hesabınıza giriş yapmıyoruz ve sizin adınıza hiçbir şey yayınlamıyoruz. Hizmet, harici ve aşamalı bir tanıtıma dayanır."], ["Kampanya ne zaman başlar?", "Hazırlık ödeme onayından sonra başlar. Dağıtım aşamalıdır ve seçilen hacme göre birkaç gün sürebilir."], ["Hacme ulaşılmazsa ne olur?", "Destek ekibimiz kampanyayı inceler ve planlanan hacme ulaşılmadığında tanıtımı ek ücret ödemeden uzatabilir."], ["İstatistikler hemen görünür mü?", "İstatistikler X'in kendi kontrol ve gecikmelerine göre değişebilir. Dağıtım aşamalı ve takip edilir kalır."]] },
    footer: { desc: "AI destekli online varlık stratejisi. Odaklı kampanyalar, net takip ve ölçülü ilerleme.", networks: "Ağlar", help: "Yardım", how: "Nasıl çalışır", support: "Kampanya desteği", tracking: "Sipariş takibi", legal: "Yasal", legalNotice: "Yasal bilgiler", privacy: "Gizlilik", cookies: "Çerezler", madeIn: "Made in Paris" },
  },
} as const;

type Widen<T> = T extends string ? string : T extends readonly (infer U)[] ? readonly Widen<U>[] : T extends object ? { readonly [K in keyof T]: Widen<T[K]> } : T;
type XCopy = Widen<(typeof copy)["en"]>;

const localized: Record<SupportedLocale, XCopy> = {
  fr: copy.fr,
  en: copy.en,
  es: copy.es,
  pt: copy.pt,
  de: copy.de,
  it: copy.it,
  tr: copy.tr,
};

export function useXCopy() {
  const { locale } = useI18n();
  const { mode, surfaceMode } = useMarketingMode();
  const manualLocale =
    typeof window !== "undefined" && window.localStorage.getItem("fanovera_locale_mode") === "manual"
      ? (window.localStorage.getItem("fanovera_locale") as SupportedLocale | null)
      : null;
  const activeLocale = manualLocale || locale;
  const base = applyPerformanceProductCopy(localized[activeLocale] || copy.fr, {
    locale: activeLocale,
    mode,
    product: "X",
    audience: "Followers",
  });
  return applyBlackhatProductCopy(base, surfaceMode, { locale: activeLocale, product: "X", audience: "Followers" });
}
